<font color="green">*To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.*</font>

# 1. SQL Programming - Text, Time and Date Strings

## 1.0 Connecting to our Database

In [ ]:
# We will first load the sql extension into our environment
%load_ext sql

# Then connect to our in memory sqlite database
# NB: This database will cease to exist as soon as the database connection is closed. 
%sql sqlite://

'Connected: @None'

Datasets used in this notebook:


1.   **Main Lighting Energy Sources averaged to Districts in 2009**

> ([Dataset Download Link](https://drive.google.com/a/moringaschool.com/file/d/1XyZwH35bo99OZIAGHH8LMN48stLwyG-b/view?usp=sharing))

2.   **Kisumu County Energy and Mining Project Implementation Status** 

> ([Dataset Download Link](https://drive.google.com/a/moringaschool.com/file/d/1awhsX-tmd_RvM1PxPhhg21GTFuDn34ca/view?usp=sharing))

3. **Population by District**

>  ([Dataset Download Link](https://drive.google.com/a/moringaschool.com/file/d/1ZpbtJ-YAzfAtnQ4k-R_zpEbYRvP5lZhr/view?usp=sharing))

4. **Visitors to Kenya between 1991 to 2014**

>  ([Dataset Download Link](https://drive.google.com/a/moringaschool.com/file/d/1FJs1YU76tRyHEtHU6w62LYQlR8Jz_4d1/view?usp=sharing))

5. **Boston Marathon Results 2016**

>  ([Dataset Download Link](https://drive.google.com/a/moringaschool.com/file/d/1FKhXZemUZuwYSJydUDgukyqJt3ouvKGi/view?usp=sharing))

6. **Kenyan Government Appointments**

>  ([Dataset Download Link](https://drive.google.com/a/moringaschool.com/file/d/19m7bydCYOyH8qb68S-Jn-dAX0TrjSHKh/view?usp=sharing))

7. **Tea Production**

>  ([Dataset Download Link](https://drive.google.com/open?id=1Nf3SfkLuxK8oWX2m_RAOILLrpY7pFDaF))

## 1.1 Loading our Datasets

In [ ]:
# Importing Pandas
import pandas as pd

In [ ]:
# Loading our lighting dataset  from the respective CSV file 
with open('/content/lighting_dataset.csv','r') as f:
    LightingDataset = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE if EXISTS LightingDataset;
%sql PERSIST LightingDataset;
%sql SELECT * FROM LightingDataset LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('MERU CENTRAL', 'Urban', None, None, None, None, None, None, None, None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'EASTERN', 'Meru', 'Table 10b: Urban Households by main type of Lighting Fuel', 'Physical Infrastructure', 'Energy', 37.58330732, 0.001443681, '(0.001443681, 37.58330732)', 0),
 ('KAKAMEGA SOUTH', 'Urban', None, None, None, None, None, None, None, None, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'WESTERN', 'Kakamega', 'Table 10a: Rural Households by main type of Lighting Fuel', 'Physical Infrastructure', 'Energy', 34.7077479, 0.190561619, '(0.190561619, 34.7077479)', 1),
 ('NYANDARUA NORTH', 'Urban', '6.3%', '0.6%', '51.6%', '32.1%', '0.8%', '0.4%', '7.9%', '0.2%', 52503, 3332, 302, 27102, 16865, 395, 214, 4173, 120, 'CENTRAL', 'Nyandarua', 'Table 10b: Urban Households by main type of Lighting Fuel', 'Physical Infrastructure', 'Energy', 36.42343108, -0.144560572, '(-0.144560572, 36.42343108)', 2),
 ('NYANDARUA SOUTH', 'Urban', '6%', '0.6%', '62.8%', '24.3%', '0.6%', '0.2%', '5.3%', '0.1%', 61936, 3741, 387, 38900, 15077, 384, 103, 3256, 88, 'CENTRAL', 'Nyandarua', 'Table 10b: Urban Households by main type of Lighting Fuel', 'Physical Infrastructure', 'Energy', 36.55651343, -0.533045224, '(-0.533045224, 36.55651343)', 3),
 ('NYERI NORTH', 'Urban', '14.5%', '1%', '41.4%', '34.3%', '0.6%', '0.8%', '7.2%', '0.2%', 81307, 11774, 775, 33686, 27884, 514, 651, 5868, 155, 'CENTRAL', 'Nyeri', 'Table 10b: Urban Households by main type of Lighting Fuel', 'Physical Infrastructure', 'Energy', 36.9811441, -0.266587082, '(-0.266587082, 36.9811441)', 4)]

In [ ]:
# Loading our energy mining dataset from the respective CSV file 
with open('/content/energy_mining_dataset.csv','r') as f:
    EnergyMining = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE if EXISTS EnergyMining;
%sql PERSIST EnergyMining;
%sql SELECT * FROM EnergyMining LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('Kisumu', 'West Kisumu', 'Huma market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 0),
 ('Kisumu', 'North west ksm', 'Daraja Mbili market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100% Complete', 'May-31-2015', 1),
 ('Kisumu', 'West Seme', 'Akado market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 2),
 ('Kisumu', 'Kobura', 'Korowe market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 3),
 ('Kisumu', 'Kobura', 'Rabour market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 4)]

In [ ]:
# Loading our population by districtdataset from the respective CSV file
with open('/content/population_by_district.csv','r') as f:
  PopulationByDistrict = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE IF EXISTS PopulationByDistrict;
%sql PERSIST  PopulationByDistrict;
%sql SELECT * FROM PopulationByDistrict LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('NAIROBI WEST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI WEST, NAIROBI Kenya\n', None, 36.79920201, 0),
 ('NAIROBI EAST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI EAST, NAIROBI Kenya\n', None, 36.967484000000006, 1),
 ('NAIROBI NORTH', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI NORTH, NAIROBI Kenya\n', None, 36.8911257, 2),
 ('WESTLANDS', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'WESTLANDS, NAIROBI Kenya\n', None, 36.7882561, 3),
 ('NYANDARUA NORTH', 'Rural', 106111, 109785, 215896, 52503, 1394.69, 37.64, 109861.0821, 1.034624, 'CENTRAL', 'NYANDARUA NORTH, CENTRAL Kenya\n', None, 36.42343108, 4)]

In [ ]:
# Loading our visitors to kenya dataset from the respective CSV file
with open('/content/visitors_to_kenya.csv','r') as f:
      visitorstokenya = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE IF EXISTS visitorstokenya;
%sql PERSIST visitorstokenya;
%sql SELECT * FROM visitorstokenya LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('Arrivals', '03/31/2005 12:00:00 AM', '2005', 264600, 'Visitors on Holiday', 'Q1', 'Actual', 0),
 ('Arrivals', '06/30/1991 12:00:00 AM', '1991', 149400, 'Visitors on Holiday', 'Q2', 'Actual', 1),
 ('Arrivals', '09/30/1991 12:00:00 AM', '1991', 215900, 'Visitors on Holiday', 'Q3', 'Actual', 2),
 ('Arrivals', '12/31/1991 12:00:00 AM', '1991', 158400, 'Visitors on Holiday', 'Q4', 'Actual', 3),
 ('Arrivals', '03/31/1992 12:00:00 AM', '1992', 155400, 'Visitors on Holiday', 'Q1', 'Actual', 4)]

In [ ]:
# Loading our marathon dataset from the respective CSV file
#
with open('/content/marathon_results_2016.csv','r') as f:
      MarathonResults = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE IF EXISTS MarathonResults;
%sql PERSIST MarathonResults;
%sql SELECT * FROM MarathonResults LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('5', 'Hayle, Lemi Berhanu', 21, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:47', '0:31:20', '0:47:07', '1:03:14', '1:06:45', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:04', '2:12:45', '2:12:45', 1, 1, 1),
 ('1', 'Desisa, Lelisa', 26, 'M', 'Ambo', None, 'ETH', None, None, '0:15:47', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:06', '2:13:32', '2:13:32', 2, 2, 2),
 ('6', 'Tsegay, Yemane Adhane', 31, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:46', '0:31:20', '0:47:07', '1:03:13', '1:06:44', '1:19:15', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:02', '2:14:02', 3, 3, 3),
 ('11', 'Korir, Wesley', 33, 'M', 'Kitale', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:07', '1:03:14', '1:06:46', '1:19:16', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:05', '2:14:05', 4, 4, 4),
 ('14', 'Lonyangata, Paul', 23, 'M', 'Eldoret', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:18', '1:34:46', '1:51:30', '2:08:11', '0:05:11', '2:15:45', '2:15:45', 5, 5, 5)]

In [ ]:
# Loading our Kenyan government appointments dataset below
#
with open('/content/government_appointments.csv','r') as f:
      governmentappointments = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE IF EXISTS governmentappointments;
%sql PERSIST governmentappointments;
%sql SELECT * FROM governmentappointments LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[(2827, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Gershom Otachi', 'Chairperson', '04/17/2015 12:00:00 AM', '05/20/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Geothermal Development Company', 36.0, 'Appointed ', 'm', None, None, 0),
 (2828, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Sammy Choge', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Chemelil Sugar Company', 36.0, 'Appointed ', 'm', None, None, 1),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Musa Sirma', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 2),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Susan Akinyi Wakiaga', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 3),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Joseph Miriti Mwereria', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 4)]

In [ ]:
# Loading our Tea dataset below
#
with open('/content/tea_production.csv','r') as f:
      teaproduction = pd.read_csv(f, index_col=0, encoding='utf-8')
%sql DROP TABLE IF EXISTS teaproduction;
%sql PERSIST teaproduction;
%sql SELECT * FROM teaproduction LIMIT 5;

 * sqlite://
Done.
 * sqlite://
 * sqlite://
Done.

[('Production', 32.8, '01/25/2003 12:00:00 AM', 0),
 ('Production', 23.6, '02/25/2003 12:00:00 AM', 1),
 ('Production', 15.0, '03/25/2003 12:00:00 AM', 2),
 ('Production', 19.3, '04/25/2003 12:00:00 AM', 3),
 ('Production', 26.0, '05/25/2003 12:00:00 AM', 4)]

## 1.2 Text Strings

In [ ]:
%sql SELECT * FROM EnergyMining;

 * sqlite://
Done.

[('Kisumu', 'West Kisumu', 'Huma market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 0),
 ('Kisumu', 'North west ksm', 'Daraja Mbili market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100% Complete', 'May-31-2015', 1),
 ('Kisumu', 'West Seme', 'Akado market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 2),
 ('Kisumu', 'Kobura', 'Korowe market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 3),
 ('Kisumu', 'Kobura', 'Rabour market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 4),
 ('Kisumu', 'Chemelil/Tamu', 'Chemelil Market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 5),
 ('Kisumu', 'East Kolwa', 'Orongo market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 6),
 ('Kisumu', 'Central Seme', 'Kombewa market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 7),
 ('Kisumu', 'South East-Nyakach ', 'Nyakach Water', 'Supply, installation & Testing of pumps motor and array of solar panels ', '80% Complete', 'May-31-2015', 8),
 ('Kisumu', 'South West-Nyakach', 'Andingo Rongo Dispensary ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 9),
 ('Kisumu', 'South West-Nyakach', 'Alara Border market ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 10),
 ('Kisumu', 'Muhoroni/Koru', 'Jaber dispensary ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 11),
 ('Kisumu', 'Muhoroni/Koru', 'Cheptuyet dispensary  ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 12),
 ('Kisumu', 'North Nyakach', 'Rae Rice mil', 'Installation of Service line', '100 % Complete', 'May-31-2015', 13),
 ('Kisumu', 'All Wards', 'Country Wide', 'Mining Inventory/GIS mapping', '100 % Complete', 'May-31-2015', 14),
 ('Kisumu', 'North Nyakach', 'Katito market market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 15),
 ('Kisumu', 'Awasi Onjiko', 'Awasi market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 16),
 ('Kisumu', 'West Nyakach', 'Nyakwere market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 17),
 ('Kisumu', 'Masogonyang�oma', 'Masogo market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 18),
 ('Kisumu', 'Miwani', 'Jua Kali market', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 19),
 ('Kisumu', 'South West-Kisumu', 'Obambo market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 20),
 ('Kisumu', 'North Seme', 'Bar market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 21),
 ('Kisumu', 'Kobura', 'Okana market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 22),
 ('Kisumu', 'Market Milimani', 'Ondiek ground', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 23),
 ('Kisumu', 'Central Seme', 'Riat Mireri market', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 24),
 ('Kisumu', 'Kabonyokanyagwal', 'Nyang�ande market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 25),
 ('Kisumu', 'SE-Nyakach', 'Bodi market ', 'Construction of 15m High mast flood lights', '100 % Complete under defect liability period', 'May-31-2016', 26),
 ('Kisumu', 'Kajulu ', 'Wathorego market ', 'Construction of 15m High mast flood lights', '100 % Complete under defect liability period', 'May-31-2016', 27),
 ('Kisumu', 'Muhoroni/Koru', 'Koru market', 'Construction of 15m High mast flood lights', '100 % Complete under defect liability period', 'May-31-2016', 28),
 ('Kisumu', 'North Seme', 'Onyinjo Dispensary ', 'Construction of 15m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 29),
 ('Kisumu', 'Ombeyi', 'Ombeyi market', 'Construction of 15m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 30),
 ('Kisumu', 'Railways ', 'Ragumo', 'Installation of Service line', '100 % Complete', 'May-31-2016', 31),
 ('Kisumu', 'Railways ', 'Kanyakwar Community Hall', 'Installation of Service line', '100 % Complete', 'May-31-2016', 32),
 ('Kisumu', 'All Wards', 'Country Wide', 'Supply of solar lanterns (800 No.) Operation Nyang�ile Out', 'Distribution on going in all the Sub-County', 'May-31-2016', 33),
 ('Kisumu', 'All Wards', 'Country Wide', 'Supply of solar lanterns (210 No.) Operation Nyang�ile Out', 'Distribution on going in all the Sub-County', 'May-31-2016', 34),
 ('Kisumu', 'All Wards', 'Country Wide', 'Supply of solar lanterns (350 No.) Operation Nyang�ile Out', 'Delivered awaiting distribution', 'May-31-2016', 35),
 ('Kisumu', 'All Wards', 'Country Wide', 'County Energy Master Plan', 'On-going 40% Complete', 'May-31-2016', 36),
 ('Kisumu', 'Central Seme', 'Kombewa District Hospital', 'County Energy Auditing ', '100 % Complete', 'May-31-2016', 37),
 ('Kisumu', 'All Wards', 'Country Wide', 'Preparation of a County Energy & Mining Strategic Plan.', '100 % Complete', 'May-31-2016', 38),
 ('Kisumu', 'SE-Nyakach', 'Nyakach sub counties ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 39),
 ('Kisumu', 'East Kano wawidhi', 'Nyando  sub counties', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 40),
 ('Kisumu', 'West Kisumu', 'Kisumu West sub counties  ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 41),
 ('Kisumu', 'North West-Kisumu', 'Kisumu West sub counties  ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 42),
 ('Kisumu', 'Kajulu', 'Kisumu East sub counties ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 43),
 ('Kisumu', 'Central Seme', 'Seme sub counties', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 44),
 ('Kisumu', 'Central Seme', 'Seme sub counties ', 'Development of brick making centres ', '100 % Complete', 'May-31-2016', 45),
 ('Kisumu', 'East Kano wawidhi', 'Nyando  sub counties', 'Development of brick making centres ', '100 % Complete', 'May-31-2016', 46),
 ('Kisumu', 'South East-Nyakach', 'Nyakach sub counties', 'Development of brick making centres ', '100 % Complete', 'May-31-2016', 47)]

In [ ]:
# Example 1
# Using the EnergyMining dataset, we can concatenate (combine) 
# the Ward and County columns (i.e attributes)
# into a new column Region. Then only select 5 of those regions
#
%%sql  
SELECT *, WARD || ', ' || COUNTY AS Region
FROM EnergyMining LIMIT 5;

 * sqlite://
Done.

[('Kisumu', 'West Kisumu', 'Huma market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 0, 'West Kisumu, Kisumu'),
 ('Kisumu', 'North west ksm', 'Daraja Mbili market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100% Complete', 'May-31-2015', 1, 'North west ksm, Kisumu'),
 ('Kisumu', 'West Seme', 'Akado market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 2, 'West Seme, Kisumu'),
 ('Kisumu', 'Kobura', 'Korowe market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 3, 'Kobura, Kisumu'),
 ('Kisumu', 'Kobura', 'Rabour market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 4, 'Kobura, Kisumu')]

In [ ]:
%sql SELECT * FROM EnergyMining;

 * sqlite://
Done.

[('Kisumu', 'West Kisumu', 'Huma market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 0),
 ('Kisumu', 'North west ksm', 'Daraja Mbili market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100% Complete', 'May-31-2015', 1),
 ('Kisumu', 'West Seme', 'Akado market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 2),
 ('Kisumu', 'Kobura', 'Korowe market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 3),
 ('Kisumu', 'Kobura', 'Rabour market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 4),
 ('Kisumu', 'Chemelil/Tamu', 'Chemelil Market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 5),
 ('Kisumu', 'East Kolwa', 'Orongo market ', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 6),
 ('Kisumu', 'Central Seme', 'Kombewa market', 'Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100 % Complete', 'May-31-2015', 7),
 ('Kisumu', 'South East-Nyakach ', 'Nyakach Water', 'Supply, installation & Testing of pumps motor and array of solar panels ', '80% Complete', 'May-31-2015', 8),
 ('Kisumu', 'South West-Nyakach', 'Andingo Rongo Dispensary ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 9),
 ('Kisumu', 'South West-Nyakach', 'Alara Border market ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 10),
 ('Kisumu', 'Muhoroni/Koru', 'Jaber dispensary ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 11),
 ('Kisumu', 'Muhoroni/Koru', 'Cheptuyet dispensary  ', 'Installation of Service line', '100 % Complete', 'May-31-2015', 12),
 ('Kisumu', 'North Nyakach', 'Rae Rice mil', 'Installation of Service line', '100 % Complete', 'May-31-2015', 13),
 ('Kisumu', 'All Wards', 'Country Wide', 'Mining Inventory/GIS mapping', '100 % Complete', 'May-31-2015', 14),
 ('Kisumu', 'North Nyakach', 'Katito market market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 15),
 ('Kisumu', 'Awasi Onjiko', 'Awasi market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 16),
 ('Kisumu', 'West Nyakach', 'Nyakwere market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 17),
 ('Kisumu', 'Masogonyang�oma', 'Masogo market ', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 18),
 ('Kisumu', 'Miwani', 'Jua Kali market', 'Construction of 20m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 19),
 ('Kisumu', 'South West-Kisumu', 'Obambo market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 20),
 ('Kisumu', 'North Seme', 'Bar market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 21),
 ('Kisumu', 'Kobura', 'Okana market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 22),
 ('Kisumu', 'Market Milimani', 'Ondiek ground', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 23),
 ('Kisumu', 'Central Seme', 'Riat Mireri market', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 24),
 ('Kisumu', 'Kabonyokanyagwal', 'Nyang�ande market ', 'Construction of 15m High mast flood lights', '100 % Complete', 'May-31-2016', 25),
 ('Kisumu', 'SE-Nyakach', 'Bodi market ', 'Construction of 15m High mast flood lights', '100 % Complete under defect liability period', 'May-31-2016', 26),
 ('Kisumu', 'Kajulu ', 'Wathorego market ', 'Construction of 15m High mast flood lights', '100 % Complete under defect liability period', 'May-31-2016', 27),
 ('Kisumu', 'Muhoroni/Koru', 'Koru market', 'Construction of 15m High mast flood lights', '100 % Complete under defect liability period', 'May-31-2016', 28),
 ('Kisumu', 'North Seme', 'Onyinjo Dispensary ', 'Construction of 15m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 29),
 ('Kisumu', 'Ombeyi', 'Ombeyi market', 'Construction of 15m High mast flood lights', '100 % Complete awaiting Power Connection', 'May-31-2016', 30),
 ('Kisumu', 'Railways ', 'Ragumo', 'Installation of Service line', '100 % Complete', 'May-31-2016', 31),
 ('Kisumu', 'Railways ', 'Kanyakwar Community Hall', 'Installation of Service line', '100 % Complete', 'May-31-2016', 32),
 ('Kisumu', 'All Wards', 'Country Wide', 'Supply of solar lanterns (800 No.) Operation Nyang�ile Out', 'Distribution on going in all the Sub-County', 'May-31-2016', 33),
 ('Kisumu', 'All Wards', 'Country Wide', 'Supply of solar lanterns (210 No.) Operation Nyang�ile Out', 'Distribution on going in all the Sub-County', 'May-31-2016', 34),
 ('Kisumu', 'All Wards', 'Country Wide', 'Supply of solar lanterns (350 No.) Operation Nyang�ile Out', 'Delivered awaiting distribution', 'May-31-2016', 35),
 ('Kisumu', 'All Wards', 'Country Wide', 'County Energy Master Plan', 'On-going 40% Complete', 'May-31-2016', 36),
 ('Kisumu', 'Central Seme', 'Kombewa District Hospital', 'County Energy Auditing ', '100 % Complete', 'May-31-2016', 37),
 ('Kisumu', 'All Wards', 'Country Wide', 'Preparation of a County Energy & Mining Strategic Plan.', '100 % Complete', 'May-31-2016', 38),
 ('Kisumu', 'SE-Nyakach', 'Nyakach sub counties ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 39),
 ('Kisumu', 'East Kano wawidhi', 'Nyando  sub counties', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 40),
 ('Kisumu', 'West Kisumu', 'Kisumu West sub counties  ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 41),
 ('Kisumu', 'North West-Kisumu', 'Kisumu West sub counties  ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 42),
 ('Kisumu', 'Kajulu', 'Kisumu East sub counties ', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 43),
 ('Kisumu', 'Central Seme', 'Seme sub counties', 'Supply, training and delivery of Brick making machines', '100 % Complete', 'May-31-2016', 44),
 ('Kisumu', 'Central Seme', 'Seme sub counties ', 'Development of brick making centres ', '100 % Complete', 'May-31-2016', 45),
 ('Kisumu', 'East Kano wawidhi', 'Nyando  sub counties', 'Development of brick making centres ', '100 % Complete', 'May-31-2016', 46),
 ('Kisumu', 'South East-Nyakach', 'Nyakach sub counties', 'Development of brick making centres ', '100 % Complete', 'May-31-2016', 47)]

In [ ]:
# Example 2
# Using the main lighting dataset, we can also replace the null cells with 0
# as shown below
# 
%%sql 
SELECT PROJECT_NAME, REPLACE("STATUS", '100 % Complete', '100%') AS "Project Status" 
FROM EnergyMining;

 * sqlite://
Done.

[('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100%'),
 ('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100% Complete'),
 ('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100%'),
 ('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100%'),
 ('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100%'),
 ('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100%'),
 ('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100%'),
 ('Supply, installation & commissioning of 8 No. 30m High mast flood lights ', '100%'),
 ('Supply, installation & Testing of pumps motor and array of solar panels ', '80% Complete'),
 ('Installation of Service line', '100%'),
 ('Installation of Service line', '100%'),
 ('Installation of Service line', '100%'),
 ('Installation of Service line', '100%'),
 ('Installation of Service line', '100%'),
 ('Mining Inventory/GIS mapping', '100%'),
 ('Construction of 20m High mast flood lights', '100% awaiting Power Connection'),
 ('Construction of 20m High mast flood lights', '100% awaiting Power Connection'),
 ('Construction of 20m High mast flood lights', '100% awaiting Power Connection'),
 ('Construction of 20m High mast flood lights', '100% awaiting Power Connection'),
 ('Construction of 20m High mast flood lights', '100% awaiting Power Connection'),
 ('Construction of 15m High mast flood lights', '100%'),
 ('Construction of 15m High mast flood lights', '100%'),
 ('Construction of 15m High mast flood lights', '100%'),
 ('Construction of 15m High mast flood lights', '100%'),
 ('Construction of 15m High mast flood lights', '100%'),
 ('Construction of 15m High mast flood lights', '100%'),
 ('Construction of 15m High mast flood lights', '100% under defect liability period'),
 ('Construction of 15m High mast flood lights', '100% under defect liability period'),
 ('Construction of 15m High mast flood lights', '100% under defect liability period'),
 ('Construction of 15m High mast flood lights', '100% awaiting Power Connection'),
 ('Construction of 15m High mast flood lights', '100% awaiting Power Connection'),
 ('Installation of Service line', '100%'),
 ('Installation of Service line', '100%'),
 ('Supply of solar lanterns (800 No.) Operation Nyang�ile Out', 'Distribution on going in all the Sub-County'),
 ('Supply of solar lanterns (210 No.) Operation Nyang�ile Out', 'Distribution on going in all the Sub-County'),
 ('Supply of solar lanterns (350 No.) Operation Nyang�ile Out', 'Delivered awaiting distribution'),
 ('County Energy Master Plan', 'On-going 40% Complete'),
 ('County Energy Auditing ', '100%'),
 ('Preparation of a County Energy & Mining Strategic Plan.', '100%'),
 ('Supply, training and delivery of Brick making machines', '100%'),
 ('Supply, training and delivery of Brick making machines', '100%'),
 ('Supply, training and delivery of Brick making machines', '100%'),
 ('Supply, training and delivery of Brick making machines', '100%'),
 ('Supply, training and delivery of Brick making machines', '100%'),
 ('Supply, training and delivery of Brick making machines', '100%'),
 ('Development of brick making centres ', '100%'),
 ('Development of brick making centres ', '100%'),
 ('Development of brick making centres ', '100%')]

In [ ]:
%sql SELECT * FROM PopulationByDistrict LIMIT 4;

 * sqlite://
Done.

[('NAIROBI WEST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI WEST, NAIROBI Kenya\n', None, 36.79920201, 0),
 ('NAIROBI EAST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI EAST, NAIROBI Kenya\n', None, 36.967484000000006, 1),
 ('NAIROBI NORTH', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI NORTH, NAIROBI Kenya\n', None, 36.8911257, 2),
 ('WESTLANDS', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'WESTLANDS, NAIROBI Kenya\n', None, 36.7882561, 3)]

In [ ]:
# Example 3
# Using the Population by District dataset, we change values of County column to lowercase 
# as shown below
#
%%sql
SELECT *, LOWER(County) AS "County Name"
FROM PopulationByDistrict;

 * sqlite://
Done.

[('NAIROBI WEST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI WEST, NAIROBI Kenya\n', None, 36.79920201, 0, 'nairobi'),
 ('NAIROBI EAST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI EAST, NAIROBI Kenya\n', None, 36.967484000000006, 1, 'nairobi'),
 ('NAIROBI NORTH', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI NORTH, NAIROBI Kenya\n', None, 36.8911257, 2, 'nairobi'),
 ('WESTLANDS', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'WESTLANDS, NAIROBI Kenya\n', None, 36.7882561, 3, 'nairobi'),
 ('NYANDARUA NORTH', 'Rural', 106111, 109785, 215896, 52503, 1394.69, 37.64, 109861.0821, 1.034624, 'CENTRAL', 'NYANDARUA NORTH, CENTRAL Kenya\n', None, 36.42343108, 4, 'central'),
 ('NYANDARUA SOUTH', 'Rural', 131872, 137982, 269854, 61936, 1472.58, 42.06, 138071.5517, 1.046333, 'CENTRAL', 'NYANDARUA SOUTH, CENTRAL Kenya\n', None, 36.55651343, 5, 'central'),
 ('NYERI NORTH', 'Rural', 141423, 143971, 285394, 81307, 2253.47, 36.08, 144033.7579, 1.018017, 'CENTRAL', 'NYERI NORTH, CENTRAL Kenya\n', None, 36.9811441, 6, 'central'),
 ('NYERI SOUTH', 'Rural', 114557, 123990, 238547, 66028, 874.13, 75.54, 124121.0526, 1.082343, 'CENTRAL', 'NYERI SOUTH, CENTRAL Kenya\n', None, 36.89927916, 7, 'central'),
 ('KIRINYAGA', 'Rural', 220494, 224156, 444650, 126665, 1402.71, 90.3, 224313.1914, 1.016608, 'CENTRAL', 'KIRINYAGA, CENTRAL Kenya\n', None, 37.32018369, 8, 'central'),
 ('MURANGA NORTH', 'Rural', 151033, 163375, 314408, 87030, 913.79, 95.24, 163540.282, 1.081717, 'CENTRAL', 'MURANGA NORTH, CENTRAL Kenya\n', None, 36.98118146, 9, 'central'),
 ('MURANGA SOUTH', 'Rural', 156115, 165195, 321310, 84114, 762.77, 110.27, 165399.6685, 1.058162, 'CENTRAL', 'MURANGA SOUTH, CENTRAL Kenya\n', None, 37.05522802, 10, 'central'),
 ('KIAMBU EAST(KIAMBAA)', 'Rural', 22768, 22306, 45074, 12468, 100.4, 124.18, 22532.77291, 0.979708, 'CENTRAL', 'KIAMBU EAST(KIAMBAA), CENTRAL Kenya\n', None, 36.80546766, 11, 'central'),
 ('KIKUYU', 'Rural', 424, 398, 822, 251, 4.78, 52.51, 486.702929, 0.938679, 'CENTRAL', 'KIKUYU, CENTRAL Kenya\n', None, 36.63360077, 12, 'central'),
 ('KIAMBU WEST', 'Rural', 25493, 25508, 51001, 13465, 197.39, 68.22, 25637.15041, 1.0005879999999998, 'CENTRAL', 'KIAMBU WEST, CENTRAL Kenya\n', None, 36.62625892, 13, 'central'),
 ('LARI', 'Rural', 60632, 63263, 123895, 30779, 439.16, 70.09, 63401.063579999995, 1.043393, 'CENTRAL', 'LARI, CENTRAL Kenya\n', None, 36.67684469, 14, 'central'),
 ('GITHUNGURI', 'Rural', 63591, 65052, 128643, 33301, 166.58, 199.91, 65433.744510000004, 1.022975, 'CENTRAL', 'GITHUNGURI, CENTRAL Kenya\n', None, 36.79433274, 15, 'central'),
 ('THIKA EAST', 'Rural', 36828, 36775, 73603, 19226, 398.18, 48.28, 36867.49083, 0.998561, 'CENTRAL', 'THIKA EAST, CENTRAL Kenya\n', None, 37.23100647, 16, 'central'),
 ('THIKA WEST', 'Rural', 12299, 12188, 24487, 7283, 207.31, 35.13, 12247.32661, 0.990975, 'CENTRAL', 'THIKA WEST, CENTRAL Kenya\n', None, 37.04502993, 17, 'central'),
 ('RUIRU', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'CENTRAL', 'RUIRU, CENTRAL Kenya\n', None, 36.99460397, 18, 'central'),
 ('GATANGA', 'Rural', 54783, 56375, 111158, 29664, 307.15, 96.58, 56553.359110000005, 1.02906, 'CENTRAL', 'GATANGA, CENTRAL Kenya\n', None, 36.88791928, 19, 'central'),
 ('GATUNDU', 'Rural', 100939, 107845, 208784, 53749, 476.47, 112.81, 108056.8475, 1.068418, 'CENTRAL', 'GATUNDU, CENTRAL Kenya\n', None, 36.85558237, 20, 'central'),
 ('MOMBASA', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'COAST', 'MOMBASA, COAST Kenya\n', None, 39.6977, 21, 'coast'),
 ('KILINDINI', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'COAST', 'KILINDINI, COAST Kenya\n', None, 39.6365, 22, 'coast'),
 ('KWALE', 'Rural', 64649, 67449, 132098, 24506, 947.88, 25.85, 67517.20378, 1.043311, 'COAST', 'KWALE, COAST Kenya\n', None, 39.40753681, 23, 'coast'),
 ('KINANGO', 'Rural', 95472, 106099, 201571, 32394, 3973.04, 8.15, 106123.03, 1.11131, 'COAST', 'KINANGO, COAST Kenya\n', None, 39.10335046, 24, 'coast'),
 ('MSAMBWENI', 'Rural', 96815, 101771, 198586, 36059, 3112.07, 11.59, 101802.1095, 1.05119, 'COAST', 'MSAMBWENI, COAST Kenya\n', None, 39.16173404, 25, 'coast'),
 ('KILIFI', 'Rural', 165217, 182876, 348093, 55663, 3839.68, 14.5, 182919.0288, 1.106884, 'COAST', 'KILIFI, COAST Kenya\n', None, 39.60114414, 26, 'coast'),
 ('KALOLENI', 'Rural', 102163, 114222, 216385, 33158, 871.56, 38.04, 114339.2186, 1.1180370000000002, 'COAST', 'KALOLENI, COAST Kenya\n', None, 39.54477529, 27, 'coast'),
 ('MALINDI', 'Rural', 126308, 133467, 259775, 38704, 7696.93, 5.03, 133483.4102, 1.0566790000000001, 'COAST', 'MALINDI, COAST Kenya\n', None, 39.74330931, 28, 'coast'),
 ('TANA RIVER', 'Rural', 54531, 55719, 110250, 21389, 22270.52, 0.96, 55721.44857000001, 1.021786, 'COAST', 'TANA RIVER, COAST Kenya\n', None, 39.34922935, 29, 'coast'),
 ('TANA DELTA', 'Rural', 47216, 46544, 93760, 18146, 15613.04, 1.16, 46547.024139999994, 0.985768, 'COAST', 'TANA DELTA, COAST Kenya\n', None, 39.51654731, 30, 'coast'),
 ('LAMU', 'Rural', 42813, 38488, 81301, 17391, 6258.46, 2.78, 38494.84082, 0.8989790000000001, 'COAST', 'LAMU, COAST Kenya\n', None, 40.74388079, 31, 'coast'),
 ('TAITA', 'Rural', 87996, 84572, 172568, 41936, 13547.51, 3.1, 84578.49536, 0.961089, 'COAST', 'TAITA, COAST Kenya\n', None, 38.56492447, 32, 'coast'),
 ('TAVETA', 'Rural', 24971, 22829, 47800, 10816, 3488.47, 3.1, 22836.15815, 0.91422, 'COAST', 'TAVETA, COAST Kenya\n', None, 37.97519351, 33, 'coast'),
 ('MARSABIT', 'Rural', 15780, 15815, 31595, 6558, 2045.73, 3.21, 15822.713630000002, 1.002218, 'EASTERN', 'MARSABIT, EASTERN Kenya\n', None, 37.94495682, 34, 'eastern'),
 ('CHALBI', 'Rural', 41318, 33878, 75196, 15586, 39248.03, 0.4, 33879.05274, 0.819933, 'EASTERN', 'CHALBI, EASTERN Kenya\n', None, 37.36288736, 35, 'eastern'),
 ('LAISAMIS', 'Rural', 29088, 29971, 59059, 13248, 20133.42, 0.66, 29972.444760000002, 1.030356, 'EASTERN', 'LAISAMIS, EASTERN Kenya\n', None, 37.48344825, 36, 'eastern'),
 ('MOYALE', 'Rural', 32832, 28475, 61307, 9752, 9310.32, 1.05, 28478.526410000002, 0.867294, 'EASTERN', 'MOYALE, EASTERN Kenya\n', None, 38.80269655, 37, 'eastern'),
 ('ISIOLO', 'Rural', 23997, 22539, 46536, 9745, 15477.82, 0.63, 22540.55041, 0.939242, 'EASTERN', 'ISIOLO, EASTERN Kenya\n', None, 38.46170147, 38, 'eastern'),
 ('GARBATULLA', 'Rural', 18863, 15521, 34384, 7076, 9608.11, 0.74, 15522.963240000001, 0.8228280000000001, 'EASTERN', 'GARBATULLA, EASTERN Kenya\n', None, 38.65180184, 39, 'eastern'),
 ('MERU CENTRAL', 'Rural', 70315, 71453, 141768, 37209, 790.15, 47.09, 71541.98943, 1.016184, 'EASTERN', 'MERU CENTRAL, EASTERN Kenya\n', None, 37.58330732, 40, 'eastern'),
 ('IMENTI NORTH', 'Rural', 96455, 94604, 191059, 51419, 1515.94, 33.92, 94667.62719, 0.9808100000000001, 'EASTERN', 'IMENTI NORTH, EASTERN Kenya\n', None, 37.43552549, 41, 'eastern'),
 ('IMENTI SOUTH', 'Rural', 83596, 82722, 166318, 42793, 657.31, 65.1, 82849.17896, 0.9895450000000001, 'EASTERN', 'IMENTI SOUTH, EASTERN Kenya\n', None, 37.60133849, 42, 'eastern'),
 ('MERU SOUTH', 'Rural', 40911, 43726, 84637, 21157, 557.98, 37.92, 43799.31983, 1.068808, 'EASTERN', 'MERU SOUTH, EASTERN Kenya\n', None, 37.67297626, 43, 'eastern'),
 ('MAARA', 'Rural', 37364, 37767, 75131, 19509, 408.58, 47.75, 37858.448430000004, 1.010786, 'EASTERN', 'MAARA, EASTERN Kenya\n', None, 37.62522793, 44, 'eastern'),
 ('IGEMBE', 'Rural', 223950, 228586, 452536, 91130, 2805.76, 32.48, 228665.8179, 1.020701, 'EASTERN', 'IGEMBE, EASTERN Kenya\n', None, 38.05720532, 45, 'eastern'),
 ('TIGANIA', 'Rural', 139371, 150216, 289587, 61666, 1122.88, 54.92, 150340.1192, 1.077814, 'EASTERN', 'TIGANIA, EASTERN Kenya\n', None, 37.77333779, 46, 'eastern'),
 ('THARAKA', 'Rural', 58691, 62872, 121563, 25227, 1462.16, 17.25, 62912.13993, 1.071237, 'EASTERN', 'THARAKA, EASTERN Kenya\n', None, 38.01828449, 47, 'eastern'),
 ('EMBU', 'Rural', 106708, 110074, 216782, 56173, 630.06, 89.16, 110243.3616, 1.031544, 'EASTERN', 'EMBU, EASTERN Kenya\n', None, 37.50475286, 48, 'eastern'),
 ('MBEERE', 'Rural', 106932, 109577, 216509, 50579, 2090.86, 24.19, 109628.1426, 1.024735, 'EASTERN', 'MBEERE, EASTERN Kenya\n', None, 37.66541038, 49, 'eastern'),
 ('KITUI', 'Rural', 155446, 171802, 327248, 67254, 7172.26, 9.38, 171823.6732, 1.10522, 'EASTERN', 'KITUI, EASTERN Kenya\n', None, 38.30094003, 50, 'eastern'),
 ('MUTOMO', 'Rural', 85554, 93098, 178652, 32427, 12833.65, 2.53, 93104.66638, 1.088178, 'EASTERN', 'MUTOMO, EASTERN Kenya\n', None, 38.53912323, 51, 'eastern'),
 ('MWINGI', 'Rural', 107186, 120692, 227878, 45445, 5217.1, 8.71, 120712.5451, 1.126005, 'EASTERN', 'MWINGI, EASTERN Kenya\n', None, 38.36852014, 52, 'eastern'),
 ('KYUSO', 'Rural', 64719, 74303, 139022, 26498, 4820.1, 5.5, 74316.4269, 1.1480860000000002, 'EASTERN', 'KYUSO, EASTERN Kenya\n', None, 38.27042885, 53, 'eastern'),
 ('MACHAKOS', 'Rural', 71438, 78058, 149496, 33559, 564.55, 59.44, 78184.53972, 1.092668, 'EASTERN', 'MACHAKOS, EASTERN Kenya\n', None, 37.16409824, 54, 'eastern'),
 ('MWALA', 'Rural', 76334, 81342, 157676, 33760, 1014.01, 33.29, 81417.27934, 1.065606, 'EASTERN', 'MWALA, EASTERN Kenya\n', None, 37.52391049, 55, 'eastern'),
 ('YATTA', 'Rural', 106094, 113963, 220057, 46905, 2214.83, 21.18, 114010.9016, 1.07417, 'EASTERN', 'YATTA, EASTERN Kenya\n', None, 37.60220541, 56, 'eastern'),
 ('KANGUNDO', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'EASTERN', 'KANGUNDO, EASTERN Kenya\n', None, 37.27203719, 57, 'eastern'),
 ('MAKUENI', 'Rural', 87571, 96177, 183748, 36541, 1249.27, 29.25, 96247.09774, 1.098275, 'EASTERN', 'MAKUENI, EASTERN Kenya\n', None, 37.67253055, 58, 'eastern'),
 ('MBOONI', 'Rural', 83997, 92292, 176289, 36765, 892.62, 41.19, 92386.10162999999, 1.098754, 'EASTERN', 'MBOONI, EASTERN Kenya\n', None, 37.60666503, 59, 'eastern'),
 ('KIBWEZI', 'Rural', 111813, 114038, 225851, 45843, 3894.48, 11.77, 114066.7106, 1.019899, 'EASTERN', 'KIBWEZI, EASTERN Kenya\n', None, 38.02538524, 60, 'eastern'),
 ('NZAUI', 'Rural', 94961, 99381, 194342, 40654, 1378.37, 29.49, 99449.89369, 1.046545, 'EASTERN', 'NZAUI, EASTERN Kenya\n', None, 37.41612392, 61, 'eastern'),
 ('GARISSA', 'Rural', 40733, 32376, 73109, 11189, 4901.58, 2.28, 32384.31018, 0.7948350000000001, 'NORTH EASTERN', 'GARISSA, NORTH EASTERN Kenya\n', None, 39.56855753, 62, 'north eastern'),
 ('LAGDERA', 'Rural', 126612, 106205, 232817, 35534, 13285.02, 2.67, 106214.5304, 0.838823, 'NORTH EASTERN', 'LAGDERA, NORTH EASTERN Kenya\n', None, 39.89717479, 63, 'north eastern'),
 ('FAFI', 'Rural', 49621, 44099, 93720, 15583, 15419.55, 1.01, 44102.21806, 0.888716, 'NORTH EASTERN', 'FAFI, NORTH EASTERN Kenya\n', None, 40.43908059, 64, 'north eastern'),
 ('IJARA', 'Rural', 41782, 34964, 76746, 10701, 9778.17, 1.09, 34968.27299, 0.8368200000000001, 'NORTH EASTERN', 'IJARA, NORTH EASTERN Kenya\n', None, 40.73455516, 65, 'north eastern'),
 ('WAJIR SOUTH', 'Rural', 66842, 54728, 121570, 17030, 21540.15, 0.79, 54731.10314, 0.818767, 'NORTH EASTERN', 'WAJIR SOUTH, NORTH EASTERN Kenya\n', None, 40.34314459, 66, 'north eastern'),
 ('WAJIR NORTH', 'Rural', 73628, 61877, 135505, 17592, 8554.59, 2.06, 61885.60684, 0.8404, 'NORTH EASTERN', 'WAJIR NORTH, NORTH EASTERN Kenya\n', None, 39.5873795, 67, 'north eastern'),
 ('WAJIR EAST', 'Rural', 78399, 63219, 141618, 18414, 13307.77, 1.38, 63224.891220000005, 0.806375, 'NORTH EASTERN', 'WAJIR EAST, NORTH EASTERN Kenya\n', None, 40.36685178, 68, 'north eastern'),
 ('WAJIR WEST', 'Rural', 93597, 72796, 166393, 20716, 13067.21, 1.59, 72803.16274, 0.77776, 'NORTH EASTERN', 'WAJIR WEST, NORTH EASTERN Kenya\n', None, 39.524001500000004, 69, 'north eastern'),
 ('MANDERA CENTRAL', 'Rural', 184891, 158652, 343543, 42017, 11606.68, 3.62, 158667.9297, 0.8580840000000001, 'NORTH EASTERN', 'MANDERA CENTRAL, NORTH EASTERN Kenya\n', None, 40.72748791, 70, 'north eastern'),
 ('MANDERA EAST', 'Rural', 113535, 87460, 200995, 25892, 6069.16, 4.27, 87478.70687000001, 0.770335, 'NORTH EASTERN', 'MANDERA EAST, NORTH EASTERN Kenya\n', None, 41.29294811, 71, 'north eastern'),
 ('MANDERA WEST', 'Rural', 161628, 134022, 295650, 34273, 8120.05, 4.22, 134041.9048, 0.8292, 'NORTH EASTERN', 'MANDERA WEST, NORTH EASTERN Kenya\n', None, 40.233462200000005, 72, 'north eastern'),
 ('SIAYA', 'Rural', 238253, 271416, 509669, 120471, 1504.63, 80.07, 271574.3466, 1.139192, 'NYANZA', 'SIAYA, NYANZA Kenya\n', None, 34.3043068, 73, 'nyanza'),
 ('BONDO', 'Rural', 53823, 56643, 110466, 26023, 497.69, 52.29, 56751.14562999999, 1.052394, 'NYANZA', 'BONDO, NYANZA Kenya\n', None, 34.19064437, 74, 'nyanza'),
 ('RARIEDA', 'Rural', 63020, 68522, 131542, 30178, 400.42, 75.37, 68679.38475, 1.0873059999999999, 'NYANZA', 'RARIEDA, NYANZA Kenya\n', None, 34.33792037, 75, 'nyanza'),
 ('KISUMU EAST', 'Rural', 41091, 42394, 83485, 18041, 284.35, 63.45, 42538.50853, 1.0317100000000001, 'NYANZA', 'KISUMU EAST, NYANZA Kenya\n', None, 34.80473358, 76, 'nyanza'),
 ('KISUMU WEST', 'Rural', 65384, 72591, 137975, 31608, 352.23, 89.74, 72776.62871, 1.110226, 'NYANZA', 'KISUMU WEST, NYANZA Kenya\n', None, 34.53285818, 77, 'nyanza'),
 ('NYANDO', 'Rural', 115314, 124415, 239729, 52448, 847.6, 61.88, 124551.0477, 1.078924, 'NYANZA', 'NYANDO, NYANZA Kenya\n', None, 35.02991504, 78, 'nyanza'),
 ('HOMA BAY', 'Rural', 145981, 161346, 307327, 65649, 1067.59, 61.49, 161482.7388, 1.105253, 'NYANZA', 'HOMA BAY, NYANZA Kenya\n', None, 34.44445584, 79, 'nyanza'),
 ('SUBA', 'Rural', 96328, 99785, 196113, 40405, 1057.37, 38.21, 99876.10151000001, 1.035888, 'NYANZA', 'SUBA, NYANZA Kenya\n', None, 34.20665004, 80, 'nyanza'),
 ('RACHUONYO', 'Rural', 154325, 167978, 322303, 67930, 860.23, 78.97, 168157.3997, 1.0884690000000001, 'NYANZA', 'RACHUONYO, NYANZA Kenya\n', None, 34.70386182, 81, 'nyanza'),
 ('MIGORI', 'Rural', 121181, 132228, 253409, 51951, 1092.16, 47.57, 132338.9554, 1.091161, 'NYANZA', 'MIGORI, NYANZA Kenya\n', None, 34.30280979, 82, 'nyanza'),
 ('RONGO', 'Rural', 65240, 68914, 134154, 26880, 429.94, 62.52, 69065.7421, 1.056315, 'NYANZA', 'RONGO, NYANZA Kenya\n', None, 34.51455638, 83, 'nyanza'),
 ('KURIA WEST', 'Rural', 66766, 69496, 136262, 21501, 365.93, 58.76, 69678.45566, 1.040889, 'NYANZA', 'KURIA WEST, NYANZA Kenya\n', None, 34.51983447, 84, 'nyanza'),
 ('KURIA EAST', 'Rural', 40248, 41585, 81833, 13513, 188.03, 71.87, 41799.05095, 1.033219, 'NYANZA', 'KURIA EAST, NYANZA Kenya\n', None, 34.65699509, 85, 'nyanza'),
 ('KISII CENTRAL', 'Rural', 133883, 149234, 283117, 60739, 335.51, 181.03, 149633.0432, 1.11466, 'NYANZA', 'KISII CENTRAL, NYANZA Kenya\n', None, 34.79181187, 86, 'nyanza'),
 ('KISII SOUTH', 'Rural', 25973, 28996, 54969, 11355, 78.43, 144.78, 29327.16155, 1.11639, 'NYANZA', 'KISII SOUTH, NYANZA Kenya\n', None, 34.689569299999995, 87, 'nyanza'),
 ('MASABA', 'Rural', 67399, 75588, 142987, 31121, 193.37, 160.94, 75936.54941, 1.1215, 'NYANZA', 'MASABA, NYANZA Kenya\n', None, 34.88253143, 88, 'nyanza'),
 ('GUCHA', 'Rural', 173472, 190988, 364460, 75379, 444.13, 169.72, 191378.5883, 1.100973, 'NYANZA', 'GUCHA, NYANZA Kenya\n', None, 34.77186075, 89, 'nyanza'),
 ('GUCHA SOUTH', 'Rural', 70458, 75849, 146307, 29032, 192.6, 150.74, 76214.82555, 1.076514, 'NYANZA', 'GUCHA SOUTH, NYANZA Kenya\n', None, 34.65567846, 90, 'nyanza'),
 ('NYAMIRA', 'Rural', 125744, 137457, 263201, 56063, 337.9, 165.92, 137829.1338, 1.09315, 'NYANZA', 'NYAMIRA, NYANZA Kenya\n', None, 34.96346861, 91, 'nyanza'),
 ('MANGA', 'Rural', 41678, 46181, 87859, 19295, 111.32, 173.33, 46555.39813, 1.1080430000000001, 'NYANZA', 'MANGA, NYANZA Kenya\n', None, 34.90211779, 92, 'nyanza'),
 ('BORABU', 'Rural', 34151, 33461, 67612, 15615, 246.55, 63.33, 33599.515510000005, 0.9797959999999999, 'NYANZA', 'BORABU, NYANZA Kenya\n', None, 35.02803793, 93, 'nyanza'),
 ('TURKANA CENTRAL', 'Rural', 101846, 102536, 204382, 31217, 13990.49, 2.23, 102543.2797, 1.006775, 'RIFT VALLEY', 'TURKANA CENTRAL, RIFT VALLEY Kenya\n', None, 35.44299468, 94, 'rift valley'),
 ('TURKANA NORTH', 'Rural', 159941, 142978, 302919, 40422, 35091.54, 1.15, 142982.5578, 0.893942, 'RIFT VALLEY', 'TURKANA NORTH, RIFT VALLEY Kenya\n', None, 35.09717514, 95, 'rift valley'),
 ('TURKANA SOUTH', 'Rural', 121022, 105357, 226379, 28437, 18670.82, 1.52, 105363.4819, 0.870561, 'RIFT VALLEY', 'TURKANA SOUTH, RIFT VALLEY Kenya\n', None, 35.99979492, 96, 'rift valley'),
 ('WEST POKOT', 'Rural', 68488, 69879, 138367, 26209, 2189.2, 11.97, 69910.28448999999, 1.02031, 'RIFT VALLEY', 'WEST POKOT, RIFT VALLEY Kenya\n', None, 35.16354392, 97, 'rift valley'),
 ('POKOT NORTH', 'Rural', 77959, 78052, 156011, 25966, 3953.21, 6.57, 78071.72043, 1.001193, 'RIFT VALLEY', 'POKOT NORTH, RIFT VALLEY Kenya\n', None, 35.10600361, 98, 'rift valley'),
 ('POKOT CENTRAL', 'Rural', 87199, 88417, 175616, 32548, 2898.74, 11.23, 88447.08168999999, 1.013968, 'RIFT VALLEY', 'POKOT CENTRAL, RIFT VALLEY Kenya\n', None, 35.49402215, 99, 'rift valley'),
 ('SAMBURU CENTRAL', 'Rural', 42524, 44378, 86902, 18300, 3924.43, 4.66, 44388.83571, 1.043599, 'RIFT VALLEY', 'SAMBURU CENTRAL, RIFT VALLEY Kenya\n', None, 36.71442163, 100, 'rift valley'),
 ('SAMBURU EAST', 'Rural', 22641, 23931, 46572, 9976, 9783.15, 1.02, 23933.314290000002, 1.056976, 'RIFT VALLEY', 'SAMBURU EAST, RIFT VALLEY Kenya\n', None, 37.47389892, 101, 'rift valley'),
 ('SAMBURU NORTH', 'Rural', 27646, 24163, 51809, 10051, 7017.61, 1.43, 24166.93952, 0.874014, 'RIFT VALLEY', 'SAMBURU NORTH, RIFT VALLEY Kenya\n', None, 36.83086912, 102, 'rift valley'),
 ('TRANS NZOIA WEST', 'Rural', 117754, 121100, 238854, 47146, 622.05, 75.79, 121289.2999, 1.0284149999999999, 'RIFT VALLEY', 'TRANS NZOIA WEST, RIFT VALLEY Kenya\n', None, 34.89426897, 103, 'rift valley'),
 ('TRANS NZOIA EAST', 'Rural', 96596, 98577, 195173, 39119, 629.78, 62.12, 98730.38055, 1.020508, 'RIFT VALLEY', 'TRANS NZOIA EAST, RIFT VALLEY Kenya\n', None, 35.18029104, 104, 'rift valley'),
 ('KWANZA', 'Rural', 108501, 108809, 217310, 42605, 1106.59, 38.5, 108907.0499, 1.002839, 'RIFT VALLEY', 'KWANZA, RIFT VALLEY Kenya\n', None, 34.85810469, 105, 'rift valley'),
 ('BARINGO', 'Rural', 65136, 66242, 131378, 27309, 2420.16, 11.28, 66268.91392, 1.01698, 'RIFT VALLEY', 'BARINGO, RIFT VALLEY Kenya\n', None, 35.97415916, 106, 'rift valley'),
 ('BARINGO NORTH', 'Rural', 46228, 47561, 93789, 19734, 1703.49, 11.58, 47588.13723, 1.028835, 'RIFT VALLEY', 'BARINGO NORTH, RIFT VALLEY Kenya\n', None, 35.80555092, 107, 'rift valley'),
 ('EAST POKOT', 'Rural', 69889, 63300, 133189, 21291, 4516.81, 4.71, 63315.47309, 0.9057219999999999, 'RIFT VALLEY', 'EAST POKOT, RIFT VALLEY Kenya\n', None, 36.01860317, 108, 'rift valley'),
 ('KOIBATEK', 'Rural', 68064, 67590, 135654, 26523, 2273.55, 11.67, 67619.93732000001, 0.993036, 'RIFT VALLEY', 'KOIBATEK, RIFT VALLEY Kenya\n', None, 35.86953085, 109, 'rift valley'),
 ('ELDORET WEST', 'Rural', 123499, 123933, 247432, 47151, 1018.49, 46.3, 124054.257, 1.003514, 'RIFT VALLEY', 'ELDORET WEST, RIFT VALLEY Kenya\n', None, 35.19163187, 110, 'rift valley'),
 ('ELDORET EAST', 'Rural', 80374, 80348, 160722, 30873, 1182.97, 26.1, 80415.94255, 0.999677, 'RIFT VALLEY', 'ELDORET EAST, RIFT VALLEY Kenya\n', None, 35.41893944, 111, 'rift valley'),
 ('WARENG', 'Rural', 70614, 69852, 140466, 27773, 832.61, 33.36, 69936.81042000001, 0.989209, 'RIFT VALLEY', 'WARENG, RIFT VALLEY Kenya\n', None, 35.33850049, 112, 'rift valley'),
 ('MARAKWET', 'Rural', 89136, 90322, 179458, 37581, 1583.88, 23.73, 90378.27699, 1.013306, 'RIFT VALLEY', 'MARAKWET, RIFT VALLEY Kenya\n', None, 35.50699822, 113, 'rift valley'),
 ('KEIYO', 'Rural', 68649, 68705, 137354, 28369, 1290.0, 21.99, 68758.21628, 1.000816, 'RIFT VALLEY', 'KEIYO, RIFT VALLEY Kenya\n', None, 35.57039657, 114, 'rift valley'),
 ('NANDI NORTH', 'Rural', 80199, 80406, 160605, 31106, 730.87, 42.56, 80515.73087, 1.002581, 'RIFT VALLEY', 'NANDI NORTH, RIFT VALLEY Kenya\n', None, 35.06077368, 115, 'rift valley'),
 ('NANDI CENTRAL', 'Rural', 70344, 72075, 142419, 28367, 506.18, 56.04, 72213.97033, 1.024608, 'RIFT VALLEY', 'NANDI CENTRAL, RIFT VALLEY Kenya\n', None, 35.08490348, 116, 'rift valley'),

### <font color="green">1.2 Challenges</font>

In [ ]:
%sql SELECT * FROM governmentappointments LIMIT 5;

 * sqlite://
Done.

[(2827, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Gershom Otachi', 'Chairperson', '04/17/2015 12:00:00 AM', '05/20/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Geothermal Development Company', 36.0, 'Appointed ', 'm', None, None, 0),
 (2828, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Sammy Choge', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Chemelil Sugar Company', 36.0, 'Appointed ', 'm', None, None, 1),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Musa Sirma', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 2),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Susan Akinyi Wakiaga', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 3),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Joseph Miriti Mwereria', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 4)]

In [ ]:
# Challenge 1
# Using the Governments appointments dataset, 
# in gender field, let's replace m = 1 and f = 0
# 
%%sql
SELECT *, REPLACE(REPLACE(Gender, 'm', 1), 'f', 0) AS "Gender_UPDATE" FROM governmentappointments;

 * sqlite://
Done.

[(2827, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Gershom Otachi', 'Chairperson', '04/17/2015 12:00:00 AM', '05/20/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Geothermal Development Company', 36.0, 'Appointed ', 'm', None, None, 0, '1'),
 (2828, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Sammy Choge', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Chemelil Sugar Company', 36.0, 'Appointed ', 'm', None, None, 1, '1'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Musa Sirma', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 2, '1'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Susan Akinyi Wakiaga', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 3, '0'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Joseph Miriti Mwereria', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 4, '1'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Valeria A. P. Palapala (Dr.)', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 5, '0'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'James Munyinyi Karanja', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 6, '1'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Janet Kirui', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 7, '0'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Abdo Mohamed Bahajj', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 8, '1'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Juliet Wanjiru Karanja', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 9, '0'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Kipera Issa Athuman', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', None, None, None, 10, None),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'David Mwangi Kuria', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 11, '1'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Sammy Kipcho Choge', 'Member of the Board', None, None, '04/17/2015 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', None, 'Revoked ', 'm', 6711.0, None, 12, '1'),
 (2830, '01/01/2015 12:00:00 AM', 'Kenya Yearbook Order, 2007', None, 'Susan Wakhungu', 'Non-Executive Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Yearbook Editorial Board', 36.0, 'Appointed ', 'f', None, None, 13, '0'),
 (2831, '01/01/2015 12:00:00 AM', 'Anti-Counterfeit Act', None, 'Polycarp Igathe', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', '02/11/2016 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Anti Counterfitng Agency', 10.0, 'Appointed ', 'm', None, None, 14, '1'),
 (2832, '01/01/2015 12:00:00 AM', 'Kenya Trade Network Agency (Order no 6 of 2011)', None, 'R. E. Kibwana', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Trade Network Agency', 36.0, 'Appointed ', 'm', None, None, 15, '1'),
 (2831, '01/01/2015 12:00:00 AM', 'Anti-Counterfeit Act', None, 'Allan George Njogu Kamau', 'Chairperson', None, None, '04/17/2015 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Anti Counterfitng Agency', None, 'Revoked ', 'm', 5.0, None, 16, '1'),
 (2833, '01/01/2015 12:00:00 AM', 'Insurance Act', 487.0, 'Fausak Abass', 'Board of Trustees Chairperson ', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', '01/09/2017 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Policy Holders Compensation Fund ', 21.0, 'Appointed ', 'm', None, None, 17, '1'),
 (2833, '01/01/2015 12:00:00 AM', 'Insurance Act', 487.0, 'Gershom Otachi', 'Board of Trustees Chairperson ', None, None, '04/17/2015 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Policy Holders Compensation Fund ', None, 'Revoked ', 'm', 15765.0, None, 18, '1'),
 (2834, '01/01/2015 12:00:00 AM', 'Capital Markets Acts', None, 'James Ndegwa', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Capital Markets Authority', 36.0, 'Appointed ', 'm', None, None, 19, '1'),
 (2835, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Josiah Magut', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', '03/11/2016 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Bomas of Kenya', 11.0, 'Appointed ', 'm', None, None, 20, '1'),
 (2835, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'John Makumi', 'Chairperson', None, None, '04/17/2015 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Bomas of Kenya', None, 'Revoked ', 'm', 2926.0, None, 21, '1'),
 (2836, '01/01/2015 12:00:00 AM', 'Companies Act', 486.0, 'Walter Nyambati', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Jomo Kenyatta Foundation', 36.0, 'Appointed ', 'm', None, None, 22, '1'),
 (2837, '01/01/2015 12:00:00 AM', 'Wildlife Conservation and Management Act 2013', None, 'Richard Leakey (Dr.)', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Wildlife Service', 36.0, 'Appointed ', 'm', None, None, 23, '1'),
 (2838, '01/01/2015 12:00:00 AM', 'Companies Act', 486.0, 'Kenneth Sigilai (Dr.)', 'Board of Directors Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Electrcity Transmision Company Limited', 36.0, 'Appointed ', 'm', None, None, 24, '1'),
 (2839, '01/01/2015 12:00:00 AM', 'Kerio Valley Development Authority Act', 441.0, 'Sam Kona', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kerio Valley Development Authority', 36.0, 'Appointed ', 'm', None, None, 25, '1'),
 (2840, '01/01/2015 12:00:00 AM', 'Children Act (no 8 of 2011)', None, 'Joyce Ngugi', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'National Council for Children Services', 36.0, 'Appointed ', 'f', None, None, 26, '0'),
 (2841, '01/01/2015 12:00:00 AM', 'Privatization Act', None, 'Henry Obwocha', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Privatization Commision', 36.0, 'Appointed ', 'm', None, None, 27, '1'),
 (2842, '01/01/2015 12:00:00 AM', 'Tourism Act (no 28 of 2011) ', None, 'Omingo Magara', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya International Convention Center', 36.0, 'Appointed ', 'm', None, None, 28, '1'),
 (2843, '01/01/2015 12:00:00 AM', 'Sports Act (No 25 of 2013)', None, 'Fred Muteti', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Sports Kenya', 36.0, 'Appointed ', 'm', None, None, 29, '1'),
 (2844, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Daniel Wamahiu', 'Board of Directors Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'National Oil Corporation of Kenya', 36.0, 'Appointed ', 'm', None, None, 30, '1'),
 (2845, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Ambrose Weda', 'Board of Directors Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'South Nyanza Sugar Company', 36.0, 'Appointed ', 'm', None, None, 31, '1'),
 (2846, '01/01/2015 12:00:00 AM', 'Kenya Animal Genetics Resource Center (Order L.N. 110 of 2011) ', None, 'Geoffrey Kamau Kibui (Dr.)', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Animal Genetics Resource Center', 36.0, 'Appointed ', 'm', None, None, 32, '1'),
 (2847, '01/01/2015 12:00:00 AM', 'Kenya Veterinary Vaccines Production Institute (Order 1990)', None, 'Wabacha James (Prof.)', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Veterinary Vaccines Production Institute (Order 1990)', 36.0, 'Appointed ', 'm', None, None, 33, '1'),
 (2848, '01/01/2015 12:00:00 AM', 'Micro and Small Enterprises Act (No 55 of 2012)', None, 'Charles Waithaka', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Micro and Small Enterprises Authority', 36.0, 'Appointed ', 'M', None, None, 34, 'M'),
 (2848, '01/01/2015 12:00:00 AM', 'Micro and Small Enterprises Act (No 55 of 2012)', None, 'Paul Billy Muhia Ngungi', 'Chairperson', None, None, '04/17/2015 12:00:00 AM', 'Uhuru Kenyatta', 'President', None, 'Micro and Small Enterprises Authority', None, 'Revoked ', 'M', 2902.0, None, 35, 'M'),
 (2849, '01/01/2015 12:00:00 AM', 'Tana and Athi Rivers Development Authority Act', 443.0, 'Abdul Bahari', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Tana and Athi Rivers Development Authority', 36.0, 'Appointed ', 'm', None, None, 36, '1'),
 (2850, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Soita Shitanda', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 37, '1'),
 (2850, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'James Kapaito Toiyanga', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', None, 'Revoked ', 'm', 2894.0, None, 38, '1'),
 (2851, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'John Ngumi', 'Board of Directors Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Pipeline Company', 36.0, 'Appointed ', 'm', None, None, 39, '1'),
 (2852, '01/01/2015 12:00:00 AM', 'Coast Development Authority Act', 449.0, 'Suleiman M Kamolleh', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Coast Development Authority', 36.0, 'Appointed ', 'm', None, None, 40, '1'),
 (2852, '01/01/2015 12:00:00 AM', 'Coast Development Authority Act', 449.0, 'Martin M. Tsuma', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Coast Development Authority', 36.0, 'Appointed ', 'm', 12424.0, None, 41, '1'),
 (2853, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Nathan Psiwa (Dr.)', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Kenya Industrial Research and Development Institute', 36.0, 'Appointed ', 'm', None, None, 42, '1'),
 (2854, '01/01/2015 12:00:00 AM', 'National Cereals And Produce Board Act (Cap. 338)', None, 'Geoffrey King’ang’i Muturi (Col.)', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'National Cereals And Produce Board', 36.0, 'Appointed ', 'm', None, None, 43, '1'),
 (2855, '01/01/2015 12:00:00 AM', 'National Campaign Against Drug Abuse Authority Act, 2012', None, 'G. Nasieku Taraiya', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Joseph Nkaissery', 'Cabinet Secretary', 'Interior And Co-Ordination Of National Government', 'National Campaign Against Drug Abuse Authority ', 36.0, 'Appointed ', 'm', None, None, 44, '1'),
 (2865, '01/01/2015 12:00:00 AM', 'Postal Corporation Of Kenya Act', 411.0, 'Susan Ihane', 'Member of the Board', '04/20/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Fred Matiangi', 'Cabinet Secretary', 'Information, Communications and Technology', 'Postal Corporation of Kenya', 36.0, 'Appointed ', 'f', None, None, 45, '0'),
 (2855, '01/01/2015 12:00:00 AM', 'National Campaign Against Drug Abuse Authority Act, 2012', None, 'Charles Njagua Kanyi', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Joseph Nkaissery', 'Cabinet Secretary', 'Interior And Co-Ordination Of National Government', 'National Campaign Against Drug Abuse Authority ', 36.0, 'Appointed ', 'm', None, None, 46, '1'),
 (2855, '01/01/2015 12:00:00 AM', 'National Campaign Against Drug Abuse Authority Act, 2012', None, 'Stephen Kiptoem Mairori', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Joseph Nkaissery', 'Cabinet Secretary', 'Interior And Co-Ordination Of National Government', 'National Campaign Against Drug Abuse Authority ', 36.0, 'Appointed ', 'm', None, None, 47, '1'),
 (2856, '01/01/2015 12:00:00 AM', 'National Campaign Against Drug Abuse Authority Act, 2012', None, 'Sheikh Juma Ngao', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Joseph Nkaissery', 'Cabinet Secretary', 'Interior And Co-Ordination Of National Government', 'National Campaign Against Drug Abuse Authority ', 36.0, 'Appointed ', 'm', None, None, 48, '1'),
 (2856, '01/01/2015 12:00:00 AM', 'National Campaign Against Drug Abuse Authority Act, 2012', None, 'Wilfred Kogo (Rev.) (Dr.)', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Joseph Nkaissery', 'Cabinet Secretary', 'Interior And Co-Ordination Of National Government', 'National Campaign Against Drug Abuse Authority ', 36.0, 'Appointed ', 'm', None, None, 49, '1'),
 (2857, '01/01/2015 12:00:00 AM', 'Kenya Trade Network Agency Order, 2010 (No. 6 Of 2010)', None, 'Francis Parsimei', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Kenya Trade Networks Agency Board', 36.0, 'Appointed ', 'm', None, None, 50, '1'),
 (2857, '01/01/2015 12:00:00 AM', 'Kenya Trade Network Agency Order, 2010 (No. 6 Of 2010)', None, 'Wambui Namu', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Kenya Trade Networks Agency Board', 36.0, 'Appointed ', 'f', None, None, 51, '0'),
 (2857, '01/01/2015 12:00:00 AM', 'Kenya Trade Network Agency Order, 2010 (No. 6 Of 2010)', None, 'Esther Gicheru (Dr.)', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Kenya Trade Networks Agency Board', 36.0, 'Appointed ', 'f', None, None, 52, '0'),
 (2858, '01/01/2015 12:00:00 AM', 'Insurance Act', 487.0, 'Tom Gitogo (CEO Retirements Benefits Authority)', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Policy Holders Compensation Fund ', 36.0, 'Appointed ', 'm', None, None, 53, '1'),
 (2858, '01/01/2015 12:00:00 AM', 'Insurance Act', 487.0, 'Nderitu Mureithi (CEO Capital Markets Authority)', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Policy Holders Compensation Fund ', 36.0, 'Appointed ', 'm', None, None, 54, '1'),
 (2858, '01/01/2015 12:00:00 AM', 'Insurance Act', 487.0, 'Maurice Jumah Okumu (CEO Governor of the Central Bank of Kenya)', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Policy Holders Compensation Fund ', 36.0, 'Appointed ', 'm', None, None, 55, '1'),
 (2859, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'John Paul K. Kenduiywa', 'Director', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Industrial Development Bank', 36.0, 'Appointed ', 'm', None, None, 56, '1'),
 (2859, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Michael K. Kiswili', 'Director', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Industrial Development Bank', 36.0, 'Appointed ', 'm', None, None, 57, '1'),
 (2860, '01/01/2015 12:00:00 AM', 'Proceeds Of Crime And Anti-Money Laundering Act, 2009 (No. 9 Of 2009)', None, 'Kennedy Ogeto', 'Chairperson', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Anti-Money Laundering Advisory Board', 36.0, 'Appointed ', 'm', None, None, 58, '1'),
 (2861, '01/01/2015 12:00:00 AM', 'Proceeds Of Crime And Anti-Money Laundering Act, 2009 (No. 9 Of 2009)', None, 'Kennedy Ogeto', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Anti-Money Laundering Advisory Board', 36.0, 'Appointed ', 'm', None, None, 59, '1'),
 (2861, '01/01/2015 12:00:00 AM', 'Proceeds Of Crime And Anti-Money Laundering Act, 2009 (No. 9 Of 2009)', None, 'Freshia Mugo Waweru (Dr.)', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Henry Rotich', 'Cabinet Secretary', 'National Treasury', 'Anti-Money Laundering Advisory Board', 36.0, 'Appointed ', 'm', None, None, 60, '1'),
 (2862, '01/01/2015 12:00:00 AM', 'Housing Act', 117.0, 'Wainaina Kenyanjui', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Fred Matiangi', 'Ag. Cabinet Secretary', 'Lands, Housing and Urban Development', None, 36.0, 'Appointed ', 'm', None, None, 61, '1'),
 (2862, '01/01/2015 12:00:00 AM', 'Housing Act', 117.0, 'Gladys Mboya', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Fred Matiangi', 'Ag. Cabinet Secretary', 'Lands, Housing and Urban Development', None, 36.0, 'Appointed ', 'f', None, None, 62, '0'),
 (2862, '01/01/2015 12:00:00 AM', 'Housing Act', 117.0, 'Francis Gitau Mungai', 'Member of the Board', '04/21/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Fred Matiangi', 'Ag. Cabinet Secretary', 'Lands, Housing and Urban Development', None, 36.0, 'Appointed ', 'm', None, None, 63, '1'),

In [ ]:
%sql SELECT * FROM governmentappointments LIMIT 5;

 * sqlite://
Done.

[(2827, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Gershom Otachi', 'Chairperson', '04/17/2015 12:00:00 AM', '05/20/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Geothermal Development Company', 36.0, 'Appointed ', 'm', None, None, 0),
 (2828, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Sammy Choge', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Chemelil Sugar Company', 36.0, 'Appointed ', 'm', None, None, 1),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Musa Sirma', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 2),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Susan Akinyi Wakiaga', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 3),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Joseph Miriti Mwereria', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 4)]

In [ ]:
# Challenge 2
# Using the Governments appointments dataset, 
# Let's merge the person appointing field with the appointers position field
#
%%sql
SELECT *, Person_Appointing_|| ' ,' ||Apointers_Position AS ROLE FROM governmentappointments LIMIT 5;

 * sqlite://
Done.

[(2827, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Gershom Otachi', 'Chairperson', '04/17/2015 12:00:00 AM', '05/20/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Geothermal Development Company', 36.0, 'Appointed ', 'm', None, None, 0, 'Uhuru Kenyatta ,President'),
 (2828, '01/01/2015 12:00:00 AM', 'The State Corporations Act', 446.0, 'Sammy Choge', 'Chairperson', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Chemelil Sugar Company', 36.0, 'Appointed ', 'm', None, None, 1, 'Uhuru Kenyatta ,President'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Musa Sirma', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 2, 'Uhuru Kenyatta ,President'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Susan Akinyi Wakiaga', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'f', None, None, 3, 'Uhuru Kenyatta ,President'),
 (2829, '01/01/2015 12:00:00 AM', 'Agricultural Development Corporation Act', 444.0, 'Joseph Miriti Mwereria', 'Member of the Board', '04/17/2015 12:00:00 AM', '04/17/2015 12:00:00 AM', None, 'Uhuru Kenyatta', 'President', None, 'Agricultural Development Corporation', 36.0, 'Appointed ', 'm', None, None, 4, 'Uhuru Kenyatta ,President')]

In [ ]:
%sql SELECT * FROM PopulationByDistrict LIMIT 5;

 * sqlite://
Done.

[('NAIROBI WEST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI WEST, NAIROBI Kenya\n', None, 36.79920201, 0),
 ('NAIROBI EAST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI EAST, NAIROBI Kenya\n', None, 36.967484000000006, 1),
 ('NAIROBI NORTH', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI NORTH, NAIROBI Kenya\n', None, 36.8911257, 2),
 ('WESTLANDS', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'WESTLANDS, NAIROBI Kenya\n', None, 36.7882561, 3),
 ('NYANDARUA NORTH', 'Rural', 106111, 109785, 215896, 52503, 1394.69, 37.64, 109861.0821, 1.034624, 'CENTRAL', 'NYANDARUA NORTH, CENTRAL Kenya\n', None, 36.42343108, 4)]

In [ ]:
# Challenge 3
# Using the Population by District dataset, 
# let's change the values of the District column to lowercase 
# and display these values in a new column 
# 
%%sql
SELECT *, LOWER(District) AS "District_name" FROM PopulationByDistrict LIMIT 5;

 * sqlite://
Done.

[('NAIROBI WEST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI WEST, NAIROBI Kenya\n', None, 36.79920201, 0, 'nairobi west'),
 ('NAIROBI EAST', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI EAST, NAIROBI Kenya\n', None, 36.967484000000006, 1, 'nairobi east'),
 ('NAIROBI NORTH', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'NAIROBI NORTH, NAIROBI Kenya\n', None, 36.8911257, 2, 'nairobi north'),
 ('WESTLANDS', 'Rural', 0, 0, 0, 0, 0.0, None, None, None, 'NAIROBI', 'WESTLANDS, NAIROBI Kenya\n', None, 36.7882561, 3, 'westlands'),
 ('NYANDARUA NORTH', 'Rural', 106111, 109785, 215896, 52503, 1394.69, 37.64, 109861.0821, 1.034624, 'CENTRAL', 'NYANDARUA NORTH, CENTRAL Kenya\n', None, 36.42343108, 4, 'nyandarua north')]

## 1.3 Time Strings

In [ ]:
%sql SELECT * FROM MarathonResults LIMIT 5;

 * sqlite://
Done.

[('5', 'Hayle, Lemi Berhanu', 21, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:47', '0:31:20', '0:47:07', '1:03:14', '1:06:45', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:04', '2:12:45', '2:12:45', 1, 1, 1),
 ('1', 'Desisa, Lelisa', 26, 'M', 'Ambo', None, 'ETH', None, None, '0:15:47', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:06', '2:13:32', '2:13:32', 2, 2, 2),
 ('6', 'Tsegay, Yemane Adhane', 31, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:46', '0:31:20', '0:47:07', '1:03:13', '1:06:44', '1:19:15', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:02', '2:14:02', 3, 3, 3),
 ('11', 'Korir, Wesley', 33, 'M', 'Kitale', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:07', '1:03:14', '1:06:46', '1:19:16', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:05', '2:14:05', 4, 4, 4),
 ('14', 'Lonyangata, Paul', 23, 'M', 'Eldoret', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:18', '1:34:46', '1:51:30', '2:08:11', '0:05:11', '2:15:45', '2:15:45', 5, 5, 5)]

In [ ]:
# Example 1
# You can work with time data just like any other kind of data type 
# when it is in the time format; HH:MM:SS
# Let's answer some questions to see how this works
# Question: Which athletes took time between 15.30 and 15.59 to pass the 5K mark?
# NB: We order the results
#
%%sql 
SELECT Name, "5K" FROM MarathonResults 
WHERE "5K" > '0:15:30' and "5K" < '0:15:59' ORDER BY "5K" ASC;

 * sqlite://
Done.

[('Tsegay, Yemane Adhane', '0:15:46'),
 ('Korir, Wesley', '0:15:46'),
 ('Lonyangata, Paul', '0:15:46'),
 ('Kitwara, Sammy', '0:15:46'),
 ('Feleke, Getu', '0:15:46'),
 ('Mekonnen, Tsegaye', '0:15:46'),
 ('Kiprop, Jackson', '0:15:46'),
 ('Da Silva, Solonei', '0:15:46'),
 ('Hayle, Lemi Berhanu', '0:15:47'),
 ('Desisa, Lelisa', '0:15:47'),
 ('Chebogut, Stephen', '0:15:47'),
 ('Nageeye, Abdi', '0:15:47'),
 ('Nyasango, Cutbert', '0:15:47'),
 ('Kamijo, Norio', '0:15:47'),
 ('Kipyego, Michael', '0:15:47'),
 ('Sanabria, Alvaro', '0:15:51'),
 ('Okuti, Harbert', '0:15:53'),
 ('Burrell, Ian', '0:15:54'),
 ('Simpson, Jason M.', '0:15:54')]

In [ ]:
# Example 2
# Finding the minimum amount of time taken to cover 15K by an athlete during the marathon. 
# Hint: We use a where clause to ignore null/blank values - we will learn how to 
# deal with such values later in the course
# 
%%sql
SELECT MIN("5K") 
FROM MarathonResults 
WHERE "5K" > 0;

 * sqlite://
Done.

[('0:15:46',)]

In [ ]:
# Example 3
# What was the average time covered by all athletes past the 10K mark?
# 
%%sql
SELECT time(AVG("10K")) 
FROM MarathonResults 
WHERE "10K" > 0;

 * sqlite://
Done.

[('15:06:58',)]

### <font color="green">1.3 Challenges</font>

In [ ]:
%sql SELECT * FROM MarathonResults LIMIT 5;

 * sqlite://
Done.

[('5', 'Hayle, Lemi Berhanu', 21, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:47', '0:31:20', '0:47:07', '1:03:14', '1:06:45', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:04', '2:12:45', '2:12:45', 1, 1, 1),
 ('1', 'Desisa, Lelisa', 26, 'M', 'Ambo', None, 'ETH', None, None, '0:15:47', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:06', '2:13:32', '2:13:32', 2, 2, 2),
 ('6', 'Tsegay, Yemane Adhane', 31, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:46', '0:31:20', '0:47:07', '1:03:13', '1:06:44', '1:19:15', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:02', '2:14:02', 3, 3, 3),
 ('11', 'Korir, Wesley', 33, 'M', 'Kitale', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:07', '1:03:14', '1:06:46', '1:19:16', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:05', '2:14:05', 4, 4, 4),
 ('14', 'Lonyangata, Paul', 23, 'M', 'Eldoret', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:18', '1:34:46', '1:51:30', '2:08:11', '0:05:11', '2:15:45', '2:15:45', 5, 5, 5)]

In [ ]:
# Challenge 1
# What were the names and time of the athletes who finished the marathon before 2hrs 15min official time?
# NB: Order your names by time in ascending order
# 
%%sql
SELECT Name, "Official Time" FROM MarathonResults
WHERE "Official Time" < '2:15:0' ORDER BY "Official Time" ASC;

 * sqlite://
Done.

[('Haslet, Adrianne K.', '10:30:23'),
 ('Hayle, Lemi Berhanu', '2:12:45'),
 ('Desisa, Lelisa', '2:13:32'),
 ('Tsegay, Yemane Adhane', '2:14:02'),
 ('Korir, Wesley', '2:14:05')]

In [ ]:
# Challenge 2
# Which countries came top 3 in completing the marathon before 2hrs 15min?
#
%%sql
SELECT Country, "Official Time" FROM MarathonResults 
WHERE "Official Time" < '2:15:0' ORDER BY "Official Time" ASC LIMIT 3;

 * sqlite://
Done.

[('USA', '10:30:23'), ('ETH', '2:12:45'), ('ETH', '2:13:32')]

In [ ]:
%sql SELECT * FROM MarathonResults LIMIT 5;

 * sqlite://
Done.

[('5', 'Hayle, Lemi Berhanu', 21, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:47', '0:31:20', '0:47:07', '1:03:14', '1:06:45', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:04', '2:12:45', '2:12:45', 1, 1, 1),
 ('1', 'Desisa, Lelisa', 26, 'M', 'Ambo', None, 'ETH', None, None, '0:15:47', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:15', '1:34:17', '1:50:24', '2:05:59', '0:05:06', '2:13:32', '2:13:32', 2, 2, 2),
 ('6', 'Tsegay, Yemane Adhane', 31, 'M', 'Addis Ababa', None, 'ETH', None, None, '0:15:46', '0:31:20', '0:47:07', '1:03:13', '1:06:44', '1:19:15', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:02', '2:14:02', 3, 3, 3),
 ('11', 'Korir, Wesley', 33, 'M', 'Kitale', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:07', '1:03:14', '1:06:46', '1:19:16', '1:34:45', '1:50:48', '2:06:47', '0:05:07', '2:14:05', '2:14:05', 4, 4, 4),
 ('14', 'Lonyangata, Paul', 23, 'M', 'Eldoret', None, 'KEN', None, None, '0:15:46', '0:31:21', '0:47:08', '1:03:14', '1:06:46', '1:19:18', '1:34:46', '1:51:30', '2:08:11', '0:05:11', '2:15:45', '2:15:45', 5, 5, 5)]

In [ ]:
# Challenge 3
# How many athletes ran 30K under 1hr 34min? Name these athletes.
# 
%%sql
SELECT COUNT(Name) AS "Number of artists who ran 30k under 1hr 34min" FROM MarathonResults
WHERE "30K" < '1:34'

 * sqlite://
Done.

[(24,)]

## 1.4 Date Strings

In [ ]:
# Example 1
# At times we would like to work with the data that is stored in the form of dates
# However, this kind of data can be really difficult to work with if it is not stored
# in datetime Data Type i.e. YYYY-MM-DD HH:MM:SS. It can even be misleading while 
# performing operations to our data. 
# Thus, when we get a dataset such as the one previewed below we will note that the datetime data 
# within the "Date_End_of_Quater" column is not in the datetime Data Type. 
# We will need to fix this;
# 
%sql SELECT * FROM visitorstokenya LIMIT 5;

 * sqlite://
Done.

[('Arrivals', '03/31/2005 12:00:00 AM', '2005', 264600, 'Visitors on Holiday', 'Q1', 'Actual', 0),
 ('Arrivals', '06/30/1991 12:00:00 AM', '1991', 149400, 'Visitors on Holiday', 'Q2', 'Actual', 1),
 ('Arrivals', '09/30/1991 12:00:00 AM', '1991', 215900, 'Visitors on Holiday', 'Q3', 'Actual', 2),
 ('Arrivals', '12/31/1991 12:00:00 AM', '1991', 158400, 'Visitors on Holiday', 'Q4', 'Actual', 3),
 ('Arrivals', '03/31/1992 12:00:00 AM', '1992', 155400, 'Visitors on Holiday', 'Q1', 'Actual', 4)]

In [ ]:
# Example 2
# In order to convert this kind of data to this format YYYY-MM-DD HH:MM:SS, 
# we would need to use the substring function. 
# An example of how the SQL substring function works is as shown in the SQL command
# in this cell;
# NB: Run this cell several times as you make changes to the numerial parameters 1, 6 
# and then observe the output after running this cell
#
%%sql
SELECT substr('SQL Tutorial', 1, 6) AS ExtractString;

 * sqlite://
Done.

[('SQL Tu',)]

In [ ]:
%sql SELECT * FROM visitorstokenya LIMIT 5;

 * sqlite://
Done.

[('Arrivals', '03/31/2005 12:00:00 AM', '2005', 264600, 'Visitors on Holiday', 'Q1', 'Actual', 0),
 ('Arrivals', '06/30/1991 12:00:00 AM', '1991', 149400, 'Visitors on Holiday', 'Q2', 'Actual', 1),
 ('Arrivals', '09/30/1991 12:00:00 AM', '1991', 215900, 'Visitors on Holiday', 'Q3', 'Actual', 2),
 ('Arrivals', '12/31/1991 12:00:00 AM', '1991', 158400, 'Visitors on Holiday', 'Q4', 'Actual', 3),
 ('Arrivals', '03/31/1992 12:00:00 AM', '1992', 155400, 'Visitors on Holiday', 'Q1', 'Actual', 4)]

In [ ]:
# Example 3
# Let's now select the "Date_End_of_Quater" data in the datetime data type format.
# We will apply the SQL substr function to the respective column
# then select the characters specifying our range then concatenating (combining)
# the selected substrings.
#  
%%sql
SELECT substr("Date_End_of_Quater", 7, 4)
|| "-" || substr("Date_End_of_Quater", 1, 2)
|| "-" || substr("Date_End_of_Quater", 4, 2)  
|| " " || substr("Date_End_of_Quater", 12,9)
AS New_Date_End_of_Quarter
FROM visitorstokenya Limit 5;

 * sqlite://
Done.

[('2005-03-31 12:00:00 ',),
 ('1991-06-30 12:00:00 ',),
 ('1991-09-30 12:00:00 ',),
 ('1991-12-31 12:00:00 ',),
 ('1992-03-31 12:00:00 ',)]

In [ ]:
# Example 4
# Once we are certain that the selected data is in the datetime data type format,
# we can then update the table as shown; Remember we learnt how to update data 
# in our table last week? :) 
# This will allow us to start using that updated table for further investigation
# 
%%sql
UPDATE visitorstokenya 
set "Date_End_of_Quater" = substr("Date_End_of_Quater", 7, 4)
|| "-" || substr("Date_End_of_Quater", 1, 2)
|| "-" || substr("Date_End_of_Quater", 4, 2)  
|| " " || substr("Date_End_of_Quater", 12,9)

 * sqlite://
832 rows affected.

[]

In [ ]:
# Example 5
# We can preview our dataset below so as to note the changes we have made to our 
# "Date_End_of_Quater" column which now looks super :) 
# 
%%sql
SELECT * 
FROM visitorstokenya Limit 5;

 * sqlite://
Done.

[('Arrivals', '2005-03-31 12:00:00 ', '2005', 264600, 'Visitors on Holiday', 'Q1', 'Actual', 0),
 ('Arrivals', '1991-06-30 12:00:00 ', '1991', 149400, 'Visitors on Holiday', 'Q2', 'Actual', 1),
 ('Arrivals', '1991-09-30 12:00:00 ', '1991', 215900, 'Visitors on Holiday', 'Q3', 'Actual', 2),
 ('Arrivals', '1991-12-31 12:00:00 ', '1991', 158400, 'Visitors on Holiday', 'Q4', 'Actual', 3),
 ('Arrivals', '1992-03-31 12:00:00 ', '1992', 155400, 'Visitors on Holiday', 'Q1', 'Actual', 4)]

In [ ]:
# Example 6
# We now continue into investigating our dataset; We answer the following question;
# Which arrivals and depatures happened before 10th June, 1991?  
# Solution:
#
%%sql
SELECT * 
FROM visitorstokenya 
WHERE "Date_End_of_Quater" < '1991-6-10';

 * sqlite://
Done.

[('Arrivals', '1991-06-30 12:00:00 ', '1991', 149400, 'Visitors on Holiday', 'Q2', 'Actual', 1),
 ('Arrivals', '1991-09-30 12:00:00 ', '1991', 215900, 'Visitors on Holiday', 'Q3', 'Actual', 2),
 ('Arrivals', '1991-12-31 12:00:00 ', '1991', 158400, 'Visitors on Holiday', 'Q4', 'Actual', 3),
 ('Arrivals', '1991-03-31 12:00:00 ', '1991', 149600, 'Visitors on Holiday', 'Q1', 'Actual', 52),
 ('Departures', '1991-03-31 12:00:00 ', '1991', 149300, 'Visitors on Holiday', 'Q1', 'Actual', 128),
 ('Departures', '1991-06-30 12:00:00 ', '1991', 111200, 'Visitors on Holiday', 'Q2', 'Actual', 148),
 ('Departures', '1991-09-30 12:00:00 ', '1991', 156200, 'Visitors on Holiday', 'Q3', 'Actual', 168),
 ('Departures', '1991-12-31 12:00:00 ', '1991', 142800, 'Visitors on Holiday', 'Q4', 'Actual', 204),
 ('Arrivals', '1991-06-30 12:00:00 ', '1991', 16600, 'Visitors on Business', 'Q2', 'Actual', 209),
 ('Arrivals', '1991-09-30 12:00:00 ', '1991', 23100, 'Visitors on Business', 'Q3', 'Actual', 210),
 ('Arrivals', '1991-12-31 12:00:00 ', '1991', 20000, 'Visitors on Business', 'Q4', 'Actual', 211),
 ('Arrivals', '1991-03-31 12:00:00 ', '1991', 17900, 'Visitors on Business', 'Q1', 'Actual', 260),
 ('Departures', '1991-03-31 12:00:00 ', '1991', 16400, 'Visitors on Business', 'Q1', 'Actual', 336),
 ('Departures', '1991-06-30 12:00:00 ', '1991', 17900, 'Visitors on Business', 'Q2', 'Actual', 356),
 ('Departures', '1991-09-30 12:00:00 ', '1991', 17800, 'Visitors on Business', 'Q3', 'Actual', 376),
 ('Departures', '1991-12-31 12:00:00 ', '1991', 16400, 'Visitors on Business', 'Q4', 'Actual', 412),
 ('Arrivals', '1991-06-30 12:00:00 ', '1991', 5100, 'Visitors in Transit', 'Q2', 'Actual', 417),
 ('Arrivals', '1991-09-30 12:00:00 ', '1991', 13200, 'Visitors in Transit', 'Q3', 'Actual', 418),
 ('Arrivals', '1991-12-31 12:00:00 ', '1991', 12500, 'Visitors in Transit', 'Q4', 'Actual', 419),
 ('Arrivals', '1991-03-31 12:00:00 ', '1991', 7500, 'Visitors in Transit', 'Q1', 'Actual', 468),
 ('Departures', '1991-03-31 12:00:00 ', '1991', 11800, 'Visitors in Transit', 'Q1', 'Actual', 544),
 ('Departures', '1991-06-30 12:00:00 ', '1991', 11100, 'Visitors in Transit', 'Q2', 'Actual', 564),
 ('Departures', '1991-09-30 12:00:00 ', '1991', 11700, 'Visitors in Transit', 'Q3', 'Actual', 584),
 ('Departures', '1991-12-31 12:00:00 ', '1991', 12600, 'Visitors in Transit', 'Q4', 'Actual', 620),
 ('Arrivals', '1991-06-30 12:00:00 ', '1991', 2400, 'Other', 'Q2', 'Actual', 625),
 ('Arrivals', '1991-09-30 12:00:00 ', '1991', 4100, 'Other', 'Q3', 'Actual', 626),
 ('Arrivals', '1991-12-31 12:00:00 ', '1991', 7900, 'Other', 'Q4', 'Actual', 627),
 ('Arrivals', '1991-03-31 12:00:00 ', '1991', 1000, 'Other', 'Q1', 'Actual', 676),
 ('Departures', '1991-03-31 12:00:00 ', '1991', 1800, 'Other', 'Q1', 'Actual', 752),
 ('Departures', '1991-06-30 12:00:00 ', '1991', 1200, 'Other', 'Q2', 'Actual', 772),
 ('Departures', '1991-09-30 12:00:00 ', '1991', 2200, 'Other', 'Q3', 'Actual', 792),
 ('Departures', '1991-12-31 12:00:00 ', '1991', 1100, 'Other', 'Q4', 'Actual', 828)]

In [ ]:
# Example 7
# Which arrivals and depatures happened after 30th June 2000?  
#
%%sql
SELECT * FROM visitorstokenya
WHERE Date_End_of_Quater > '2000-6-30';

 * sqlite://
Done.

[('Arrivals', '2005-31-03 12:00:00 ', '2005', 264600, 'Visitors on Holiday', 'Q1', 'Actual', 0),
 ('Arrivals', '2001-31-03 12:00:00 ', '2001', 200300, 'Visitors on Holiday', 'Q1', 'Actual', 40),
 ('Arrivals', '2001-30-06 12:00:00 ', '2001', 149600, 'Visitors on Holiday', 'Q2', 'Actual', 41),
 ('Arrivals', '2001-31-12 12:00:00 ', '2001', 194200, 'Visitors on Holiday', 'Q4', 'Actual', 43),
 ('Arrivals', '2002-31-03 12:00:00 ', '2002', 176000, 'Visitors on Holiday', 'Q1', 'Actual', 44),
 ('Arrivals', '2002-30-06 12:00:00 ', '2002', 158500, 'Visitors on Holiday', 'Q2', 'Actual', 45),
 ('Arrivals', '2002-31-12 12:00:00 ', '2002', 204000, 'Visitors on Holiday', 'Q4', 'Actual', 47),
 ('Arrivals', '2003-31-03 12:00:00 ', '2003', 206700, 'Visitors on Holiday', 'Q1', 'Actual', 48),
 ('Arrivals', '2003-30-06 12:00:00 ', '2003', 112500, 'Visitors on Holiday', 'Q2', 'Actual', 49),
 ('Arrivals', '2003-31-12 12:00:00 ', '2003', 180900, 'Visitors on Holiday', 'Q4', 'Actual', 51),
 ('Arrivals', '2005-30-06 12:00:00 ', '2005', 213400, 'Visitors on Holiday', 'Q2', 'Actual', 53),
 ('Arrivals', '2005-31-12 12:00:00 ', '2005', 2966000, 'Visitors on Holiday', 'Q4', 'Actual', 55),
 ('Arrivals', '2006-31-03 12:00:00 ', '2006', 2756000, 'Visitors on Holiday', 'Q1', 'Actual', 56),
 ('Arrivals', '2006-30-06 12:00:00 ', '2006', 219200, 'Visitors on Holiday', 'Q2', 'Actual', 57),
 ('Arrivals', '2006-31-12 12:00:00 ', '2006', 303200, 'Visitors on Holiday', 'Q4', 'Actual', 59),
 ('Arrivals', '2007-31-03 12:00:00 ', '2007', 298400, 'Visitors on Holiday', 'Q1', 'Actual', 60),
 ('Arrivals', '2007-30-06 12:00:00 ', '2007', 263000, 'Visitors on Holiday', 'Q2', 'Actual', 61),
 ('Arrivals', '2007-31-12 12:00:00 ', '2007', 336500, 'Visitors on Holiday', 'Q4', 'Actual', 63),
 ('Arrivals', '2008-31-03 12:00:00 ', '2008', 201600, 'Visitors on Holiday', 'Q1', 'Actual', 64),
 ('Arrivals', '2008-30-06 12:00:00 ', '2008', 205600, 'Visitors on Holiday', 'Q2', 'Actual', 65),
 ('Arrivals', '2008-31-12 12:00:00 ', '2008', 285200, 'Visitors on Holiday', 'Q4', 'Actual', 67),
 ('Arrivals', '2009-31-03 12:00:00 ', '2009', 258700, 'Visitors on Holiday', 'Q1', 'Actual', 68),
 ('Arrivals', '2009-30-06 12:00:00 ', '2009', 217500, 'Visitors on Holiday', 'Q2', 'Actual', 69),
 ('Arrivals', '2009-31-12 12:00:00 ', '2009', 306700, 'Visitors on Holiday', 'Q4', 'Actual', 71),
 ('Arrivals', '2010-31-03 12:00:00 ', '2010', 261200, 'Visitors on Holiday', 'Q1', 'Actual', 72),
 ('Arrivals', '2010-30-06 12:00:00 ', '2010', 228700, 'Visitors on Holiday', 'Q2', 'Actual', 73),
 ('Arrivals', '2010-30-09 12:00:00 ', '2010', 302600, 'Visitors on Holiday', 'Q3', 'Actual', 74),
 ('Arrivals', '2010-31-12 12:00:00 ', '2010', 308200, 'Visitors on Holiday', 'Q4', 'Actual', 75),
 ('Arrivals', '2011-31-03 12:00:00 ', '2011', 302800, 'Visitors on Holiday', 'Q1', 'Actual', 76),
 ('Arrivals', '2011-30-06 12:00:00 ', '2011', 235500, 'Visitors on Holiday', 'Q2', 'Actual', 77),
 ('Arrivals', '2011-30-09 12:00:00 ', '2011', 411900, 'Visitors on Holiday', 'Q3', 'Actual', 78),
 ('Arrivals', '2011-31-12 12:00:00 ', '2011', 369700, 'Visitors on Holiday', 'Q4', 'Actual', 79),
 ('Arrivals', '2012-31-03 12:00:00 ', '2012', 317000, 'Visitors on Holiday', 'Q1', 'Actual', 80),
 ('Arrivals', '2012-30-06 12:00:00 ', '2012', 240100, 'Visitors on Holiday', 'Q2', 'Actual', 81),
 ('Arrivals', '2012-30-09 12:00:00 ', '2012', 323600, 'Visitors on Holiday', 'Q3', 'Actual', 82),
 ('Arrivals', '2012-31-12 12:00:00 ', '2012', 338500, 'Visitors on Holiday', 'Q4', 'Actual', 83),
 ('Arrivals', '2013-31-03 12:00:00 ', '2013', 257600, 'Visitors on Holiday', 'Q1', 'Actual', 84),
 ('Arrivals', '2013-30-06 12:00:00 ', '2013', 222000, 'Visitors on Holiday', 'Q2', 'Actual', 85),
 ('Arrivals', '2013-30-09 12:00:00 ', '2013', 284200, 'Visitors on Holiday', 'Q3', 'Actual', 86),
 ('Arrivals', '2013-31-12 12:00:00 ', '2013', 340100, 'Visitors on Holiday', 'Q4', 'Actual', 87),
 ('Arrivals', '2004-31-03 12:00:00 ', "2004'", 209400, 'Visitors on Holiday', 'Q1', 'Preliminary ', 96),
 ('Arrivals', '2004-30-06 12:00:00 ', "2004'", 178500, 'Visitors on Holiday', 'Q2', 'Preliminary ', 97),
 ('Arrivals', '2004-31-12 12:00:00 ', '2004*', 258400, 'Visitors on Holiday', 'Q4', 'Preliminary ', 99),
 ('Arrivals', '2009-31-03 12:00:00 ', '2009*', 248600, 'Visitors on Holiday', 'Q1', 'Preliminary ', 100),
 ('Arrivals', '2009-30-06 12:00:00 ', '2009*', 211600, 'Visitors on Holiday', 'Q2', 'Preliminary ', 101),
 ('Arrivals', '2009-31-12 12:00:00 ', '2009*', 306300, 'Visitors on Holiday', 'Q4', 'Preliminary ', 103),
 ('Arrivals', '2014-31-03 12:00:00 ', '2014*', 266200, 'Visitors on Holiday', 'Q1', 'Preliminary ', 104),
 ('Arrivals', '2014-30-06 12:00:00 ', '2014*', 207000, 'Visitors on Holiday', 'Q2', 'Preliminary ', 105),
 ('Arrivals', '2014-30-09 12:00:00 ', '2014*', 267900, 'Visitors on Holiday', 'Q3', 'Preliminary ', 106),
 ('Arrivals', '2014-31-12 12:00:00 ', '2014*', 235700, 'Visitors on Holiday', 'Q4', 'Preliminary ', 107),
 ('Departures', '2001-31-12 12:00:00 ', '2001', 194200, 'Visitors on Holiday', 'Q4', 'Actual', 115),
 ('Departures', '2002-31-12 12:00:00 ', '2002', 204000, 'Visitors on Holiday', 'Q4', 'Actual', 116),
 ('Departures', '2003-31-12 12:00:00 ', '2003', 180900, 'Visitors on Holiday', 'Q4', 'Actual', 117),
 ('Departures', '2004-31-12 12:00:00 ', '2004*', 258400, 'Visitors on Holiday', 'Q4', 'Preliminary ', 118),
 ('Departures', '2005-31-12 12:00:00 ', '2005', 267000, 'Visitors on Holiday', 'Q4', 'Actual', 119),
 ('Departures', '2006-31-12 12:00:00 ', '2006', 284900, 'Visitors on Holiday', 'Q4', 'Actual', 120),
 ('Departures', '2014-31-03 12:00:00 ', '2014*', 234600, 'Visitors on Holiday', 'Q1', 'Preliminary ', 121),
 ('Departures', '2007-31-12 12:00:00 ', '2007', 295000, 'Visitors on Holiday', 'Q4', 'Actual', 122),
 ('Departures', '2014-30-06 12:00:00 ', '2014*', 205600, 'Visitors on Holiday', 'Q2', 'Preliminary ', 123),
 ('Departures', '2008-31-12 12:00:00 ', '2008', 236600, 'Visitors on Holiday', 'Q4', 'Actual', 124),
 ('Departures', '2014-30-09 12:00:00 ', '2014*', 244900, 'Visitors on Holiday', 'Q3', 'Preliminary ', 125),
 ('Departures', '2009-31-12 12:00:00 ', '2009*', 306700, 'Visitors on Holiday', 'Q4', 'Preliminary ', 126),
 ('Departures', '2014-31-12 12:00:00 ', '2014*', 260300, 'Visitors on Holiday', 'Q4', 'Preliminary ', 127),
 ('Departures', '2001-31-03 12:00:00 ', '2001', 200300, 'Visitors on Holiday', 'Q1', 'Actual', 139),
 ('Departures', '2002-31-03 12:00:00 ', '2002', 176000, 'Visitors on Holiday', 'Q1', 'Actual', 140),
 ('Departures', '2003-31-03 12:00:00 ', '2003', 206700, 'Visitors on Holiday', 'Q1', 'Actual', 141),
 ('Departures', '2004-31-03 12:00:00 ', '2004*', 209400, 'Visitors on Holiday', 'Q1', 'Preliminary ', 142),
 ('Departures', '2005-31-03 12:00:00 ', '2005', 258900, 'Visitors on Holiday', 'Q1', 'Actual', 143),
 ('Departures', '2006-31-03 12:00:00 ', '2006', 285300, 'Visitors on Holiday', 'Q1', 'Actual', 144),
 ('Departures', '2007-31-03 12:00:00 ', '2007', 314200, 'Visitors on Holiday', 'Q1', 'Actual', 145),
 ('Departures', '2008-31-03 12:00:00 ', '2008', 210100, 'Visitors on Holiday', 'Q1', 'Actual', 146),
 ('Departures', '2009-31-03 12:00:00 ', '2009*', 258700, 'Visitors on Holiday', 'Q1', 'Preliminary ', 147),
 ('Departures', '2001-30-06 12:00:00 ', '2001', 149600, 'Visitors on Holiday', 'Q2', 'Actual', 159),
 ('Departures', '2002-30-06 12:00:00 ', '2002', 158500, 'Visitors on Holiday', 'Q2', 'Actual', 160),
 ('Departures', '2003-30-06 12:00:00 ', '2003', 112500, 'Visitors on Holiday', 'Q2', 'Actual', 161),
 ('Departures', '2004-30-06 12:00:00 ', '2004*', 178500, 'Visitors on Holiday', 'Q2', 'Preliminary ', 162),
 ('Departures', '2005-30-06 12:00:00 ', '2005', 221900, 'Visitors on Holiday', 'Q2', 'Actual', 163),
 ('Departures', '2006-30-06 12:00:00 ', '2006', 232900, 'Visitors on Holiday', 'Q2', 'Actual', 164),
 ('Departures', '2007-30-06 12:00:00 ', '2007', 270200, 'Visitors on Holiday', 'Q2', 'Actual', 165),
 ('Departures', '2008-30-06 12:00:00 ', '2008', 193400, 'Visitors on Holiday', 'Q2', 'Actual', 166),
 ('Departures', '2009-30-06 12:00:00 ', '2009*', 217500, 'Visitors on Holiday', 'Q2', 'Preliminary ', 167),
 ('Departures', '2010-31-03 12:00:00 ', '2010', 265600, 'Visitors on Holiday', 'Q1', 'Actual', 173),
 ('Departures', '2010-30-06 12:00:00 ', '2010', 220200, 'Visitors on Holiday', 'Q2', 'Actual', 175),
 ('Departures', '2010-30-09 12:00:00 ', '2010', 290300, 'Visitors on Holiday', 'Q3', 'Actual', 177),
 ('Departures', '2010-31-12 12:00:00 ', '2010', 309000, 'Visitors on Holiday', 'Q4', 'Actual', 179),
 ('Departures', '2011-31-03 12:00:00 ', '2011', 277600, 'Visitors on Holiday', 'Q1', 'Actual', 181),
 ('Departures', '2011-30-06 12:00:00 ', '2011', 204900, 'Visitors on Holiday', 'Q2', 'Actual', 183),
 ('Departures', '2011-30-09 12:00:00 ', '2011', 322800, 'Visitors on Holiday', 'Q3', 'Actual', 185),
 ('Departures', '2001-30-09 12:00:00 ', '2001', 184700, 'Visitors on Holiday', 'Q3', 'Actual', 186),
 ('Departures', '2011-31-12 12:00:00 ', '2011', 314200, 'Visitors on Holiday', 'Q4', 'Actual', 187),
 ('Departures', '2002-30-09 12:00:00 ', '2002', 194100, 'Visitors on Holiday', 'Q3', 'Actual', 188),
 ('Departures', '2012-31-03 12:00:00 ', '2012', 281700, 'Visitors on Holiday', 'Q1', 'Actual', 189),
 ('Departures', '2003-30-09 12:00:00 ', '2003', 183900, 'Visitors on Holiday', 'Q3', 'Actual', 190),
 ('Departures', '2012-30-06 12:00:00 ', '2012', 216000, 'Visitors on Holiday', 'Q2', 'Actual', 191),
 ('Departures', '2004-30-09 12:00:00 ', '2004*', 239300, 'Visitors on Holiday', 'Q3', 'Preliminary ', 192),
 ('Departures', '2012-30-09 12:00:00 ', '2012', 297600, 'Visitors on Holiday', 'Q3', 'Actual', 193),
 ('Departures', '2005-30-09 12:00:00 ', '2005', 279300, 'Visitors on Holiday', 'Q3', 'Actual', 194),
 ('Departures', '2012-31-12 12:00:00 ', '2012', 289400, 'Visitors on Holiday', 'Q4', 'Actual', 195),
 ('Departures', '2006-30-09 12:00:00 ', '2006', 274900, 'Visitors on Holiday', 'Q3', 'Actual', 196),
 ('Departures', '2013-31-03 12:00:00 ', '2013', 264000, 'Visitors on Holiday', 'Q1', 'Actual', 197),
 ('Departures', '2007-30-09 12:00:00 ', '2007', 352600, 'Visitors on Holiday', 'Q3', 'Actual', 198),
 ('Departures', '2013-30-06 12:00:00 ', '2013', 206800, 'Visitors on Holiday', 'Q2', 'Actual', 199),
 ('Departures', '2008-30-09 12:00:00 ', '2008', 251500, 'Visitors on Holiday', 'Q3', 'Actual', 200),
 ('Departures', '2013-30-09 12:00:00 ', '2013', 265700, 'Visitors on Holiday', 'Q3', 'Actual', 201),
 ('Departures', '2009-30-09 12:00:00 ', '2009*', 282000, 'Visitors on Holiday', 'Q3', 'Preliminary ', 202),
 ('Departures', '2013-31-12 12:00:00 ', '2013', 323300, 'Visitors on Holiday', 'Q4', 'Actual', 203),
 ('Arrivals', '2005-31-03 12:00:00 ', '2005', 516000, 'Visitors on Business', 'Q1', 'Actual', 208),
 ('Arrivals', '2001-31-03 12:00:00 ', '2001', 25300, 'Visitors on Business', 'Q1', 'Actual', 248),
 ('Arrivals', '2001-30-06 12:00:00 ', '2001', 18900, 'Visitors on Business', 'Q2', 'Actual', 249),
 ('Arrivals', '2001-31-12 12:00:00 ', '2001', 24600, 'Visitors on Business', 'Q4', 'Actual', 251),
 ('Arrivals', '2002-31-03 12:00:00 ', '2002', 26100, 'Visitors on Business', 'Q1', 'Actual', 252),
 ('Arrivals', '2002-30-06 12:00:00 ', '2002', 17100, 'Visitors on Business', 'Q2', 'Actual', 253),
 ('Arrivals', '2002-31-12 12:00:00 ', '2002', 23000, 'Visitors on Business', 'Q4', 'Actual', 255),
 ('Arrivals', '2003-31-03 12:00:00 ', '2003', 34700, 'Visitors on Business', 'Q1', 'Actual', 256),
 ('Arrivals', '2003-30-06 12:00:00 ', '2003', 44700, 'Visitors on Business', 'Q2', 'Actual', 257),
 ('Arrivals', '2003-31-12 12:00:00 ', '2003', 49300, 'Visitors on Business', 'Q4', 'Actual', 259),
 ('Arrivals', '2005-30-06 12:00:00 ', '2005', 41900, 'Visitors on Business', 'Q2', 'Actual', 261),
 ('Arrivals', '2005-31-12 12:00:00 ', '2005', 556000, 'Visitors on Business', 'Q4', 'Actual', 263),
 ('Arrivals', '2006-31-03 12:00:00 ', '2006', 61700, 'Visitors on Business', 'Q1', 'Actual', 264),
 ('Arrivals', '2006-30-06 12:00:00 ', '2006', 456000, 'Visitors on Business', 'Q2', 'Actual', 265),
 ('Arrivals', '2006-31-12 12:00:00 ', '2006', 59600, 'Visitors on Business', 'Q4', 'Actual', 267),
 ('Arrivals', '2007-31-03 12:00:00 ', '2007', 756000, 'Visitors on Business', 'Q1', 'Actual', 268),
 ('Arrivals', '2007-30-06 12:00:00 ', '2007', 51600, 'Visitors on Business', 'Q2', 'Actual', 269),
 ('Arrivals', '2007-31-12 12:00:00 ', '2007', 50100, 'Visitors on Business', 'Q4', 'Actual', 271),
 ('Arrivals', '2008-31-03 12:00:00 ', '2008', 20400, 'Visitors on Business', 'Q1', 'Actual', 272),
 ('Arrivals', '2008-30-06 12:00:00 ', '2008', 18600, 'Visitors on Business', 'Q2', 'Actual', 273),
 ('Arrivals', '2008-31-12 12:00:00 ', '2008', 37200, 'Visitors on Business', 'Q4', 'Actual', 275),
 ('Arrivals', '2009-31-03 12:00:00 ', '2009', 38000, 'Visitors on Business', 'Q1', 'Actual', 276),
 ('Arrivals', '2009-30-06 12:00:00 ', '2009', 44400, 'Visitors on Business', 'Q2', 'Actual', 277),
 ('Arrivals', '2009-31-12 12:00:00 ', '2009', 46800, 'Visitors on Business', 'Q4', 'Actual', 279),
 ('Arrivals', '2010-31-03 12:00:00 ', '2010', 59700, 'Visitors on Business', 'Q1', 'Actual', 280),
 ('Arrivals', '2010-30-06 12:00:00 ', '2010', 48600, 'Visitors on Business', 'Q2', 'Actual', 281),
 ('Arrivals', '2010-30-09 12:00:00 ', '2010', 62000, 'Visitors on Business', 'Q3', 'Actual', 282),
 ('Arrivals', '2010-31-12 12:00:00 ', '2010', 58600, 'Visitors on Business', 'Q4', 'Actual', 283),
 ('Arrivals', '2011-31-03 12:00:00 ', '2011', 63600, 'Visitors on Business', 'Q1', 'Actual', 284),
 ('Arrivals', '2011-30-06 12:00:00 ', '2011', 56000, 'Visitors on Business', 'Q2', 'Actual', 285),
 ('Arrivals', '2011-30-09 12:00:00 ', '2011', 50100, 'Visitors on Business', 'Q3', 'Actual', 286),
 ('Arrivals', '2011-31-12 12:00:00 ', '2011', 62400, 'Visitors on Business', 'Q4', 'Actual', 287),
 ('Arrivals', '2012-31-03 12:00:00 ', '2012', 68400, 'Visitors on Business', 'Q1', 'Actual', 288),
 ('Arrivals', '2012-30-06 12:00:00 ', '2012', 58800, 'Visitors on Business', 'Q2', 'Actual', 289),
 ('Arrivals', '2012-30-09 12:00:00 ', '2012', 55700, 'Visitors on Business', 'Q3', 'Actual', 290),
 ('Arrivals', '2012-31-12 12:00:00 ', '2012', 53200, 'Visitors on Business', 'Q4', 'Actual', 291),
 ('Arrivals', '2013-31-03 12:00:00 ', '2013', 45900, 'Visitors on Business', 'Q1', 'Actual', 292),
 ('Arrivals', '2013-30-06 12:00:00 ', '2013', 47300, 'Visitors on Business', 'Q2', 'Actual', 293),
 ('Arrivals', '2013-30-09 12:00:00 ', '2013', 41700, 'Visitors on Business', 'Q3', 'Actual', 294),
 ('Arrivals', '2013-31-12 12:00:00 ', '2013', 55300, 'Visitors on Business', 'Q4', 'Actual', 295),
 ('Arrivals', '2004-31-03 12:00:00 ', "2004'", 51100, 'Visitors on Business', 'Q1', 'Preliminary ', 304),
 ('Arrivals', '2004-30-06 12:00:00 ', "2004'", 49300, 'Visitors on Business', 'Q2', 'Preliminary ', 305),
 ('Arrivals', '2004-31-12 12:00:00 ', '2004*', 75200, 'Visitors on Business', 'Q4', 'Preliminary ', 307),
 ('Arrivals', '2009-31-03 12:00:00 ', '2009*', 44100, 'Visitors on Business', 'Q1', 'Preliminary ', 308),
 ('Arrivals', '2009-30-06 12:00:00 ', '2009*', 46400, 'Visitors on Business', 'Q2', 'Preliminary ', 309),
 ('Arrivals', '2009-31-12 12:00:00 ', '2009*', 43600, 'Visitors on Business', 'Q4', 'Preliminary ', 311),
 ('Arrivals', '2014-31-03 12:00:00 ', '2014*', 50100, 'Visitors on Business', 'Q1', 'Preliminary ', 312),
 ('Arrivals', '2014-30-06 12:00:00 ', '2014*', 38500, 'Visitors on Business', 'Q2', 'Preliminary ', 313),
 ('Arrivals', '2014-30-09 12:00:00 ', '2014*', 43000, 'Visitors on Business', 'Q3', 'Preliminary ', 314),
 ('Arrivals', '2014-31-12 12:00:00 ', '2014*', 35300, 'Visitors on Business', 'Q4', 'Preliminary ', 315),
 ('Departures', '2001-31-12 12:00:00 ', '2001', 24600, 'Visitors on Business', 'Q4', 'Actual', 323),
 ('Departures', '2002-31-12 12:00:00 ', '2002', 23000, 'Visitors on Business', 'Q4', 'Actual', 324),
 ('Departures', '2003-31-12 12:00:00 ', '2003', 49300, 'Visitors on Business', 'Q4', 'Actual', 325),
 ('Departures', '2004-31-12 12:00:00 ', '2004*', 75200, 'Visitors on Business', 'Q4', 'Preliminary ', 326),
 ('Departures', '2005-31-12 12:00:00 ', '2005', 52400, 'Visitors on Business', 'Q4', 'Actual', 327),
 ('Departures', '2006-31-12 12:00:00 ', '2006', 55000, 'Visitors on Business', 'Q4', 'Actual', 328),
 ('Departures', '2014-31-03 12:00:00 ', '2014*', 53600, 'Visitors on Business', 'Q1', 'Preliminary ', 329),
 ('Departures', '2007-31-12 12:00:00 ', '2007', 53900, 'Visitors on Business', 'Q4', 'Actual', 330),
 ('Departures', '2014-30-06 12:00:00 ', '2014*', 45600, 'Visitors on Business', 'Q2', 'Preliminary ', 331),
 ('Departures', '2008-31-12 12:00:00 ', '2008', 38100, 'Visitors on Business', 'Q4', 'Actual', 332),
 ('Departures', '2014-30-09 12:00:00 ', '2014*', 45700, 'Visitors on Business', 'Q3', 'Preliminary ', 333),
 ('Departures', '2009-31-12 12:00:00 ', '2009*', 46800, 'Visitors on Business', 'Q4', 'Preliminary ', 334),
 ('Departures', '2014-31-12 12:00:00 ', '2014*', 48100, 'Visitors on Business', 'Q4', 'Preliminary ', 335),
 ('Departures', '2001-31-03 12:00:00 ', '2001', 25300, 'Visitors on Business', 'Q1', 'Actual', 347),
 ('Departures', '2002-31-03 12:00:00 ', '2002', 26100, 'Visitors on Business', 'Q1', 'Actual', 348),
 ('Departures', '2003-31-03 12:00:00 ', '2003', 34700, 'Visitors on Business', 'Q1', 'Actual', 349),
 ('Departures', '2004-31-03 12:00:00 ', '2004*', 51100, 'Visitors on Business', 'Q1', 'Preliminary ', 350),
 ('Departures', '2005-31-03 12:00:00 ', '2005', 50800, 'Visitors on Business', 'Q1', 'Actual', 351),
 ('Departures', '2006-31-03 12:00:00 ', '2006', 56700, 'Visitors on Business', 'Q1', 'Actual', 352),
 ('Departures', '2007-31-03 12:00:00 ', '2007', 65500, 'Visitors on Business', 'Q1', 'Actual', 353),
 ('Departures', '2008-31-03 12:00:00 ', '2008', 18900, 'Visitors on Business', 'Q1', 'Actual', 354),
 ('Departures', '2009-31-03 12:00:00 ', '2009*', 38000, 'Visitors on Business', 'Q1', 'Preliminary ', 355),
 ('Departures', '2001-30-06 12:00:00 ', '2001', 18900, 'Visitors on Business', 'Q2', 'Actual', 367),
 ('Departures', '2002-30-06 12:00:00 ', '2002', 17100, 'Visitors on Business', 'Q2', 'Actual', 368),
 ('Departures', '2003-30-06 12:00:00 ', '2003', 44700, 'Visitors on Business', 'Q2', 'Actual', 369),
 ('Departures', '2004-30-06 12:00:00 ', '2004*', 49300, 'Visitors on Business', 'Q2', 'Preliminary ', 370),
 ('Departures', '2005-30-06 12:00:00 ', '2005', 43600, 'Visitors on Business', 'Q2', 'Actual', 371),
 ('Departures', '2006-30-06 12:00:00 ', '2006', 47900, 'Visitors on Business', 'Q2', 'Actual', 372),
 ('Departures', '2007-30-06 12:00:00 ', '2007', 49100, 'Visitors on Business', 'Q2', 'Actual', 373),
 ('Departures', '2008-30-06 12:00:00 ', '2008', 19900, 'Visitors on Business', 'Q2', 'Actual', 374),
 ('Departures', '2009-30-06 12:00:00 ', '2009*', 44400, 'Visitors on Business', 'Q2', 'Preliminary ', 375),
 ('Departures', '2010-31-03 12:00:00 ', '2010', 40000, 'Visitors on Business', 'Q1', 'Actual', 381),
 ('Departures', '2010-30-06 12:00:00 ', '2010', 45300, 'Visitors on Business', 'Q2', 'Actual', 383),
 ('Departures', '2010-30-09 12:00:00 ', '2010', 41600, 'Visitors on Business', 'Q3', 'Actual', 385),
 ('Departures', '2010-31-12 12:00:00 ', '2010', 46200, 'Visitors on Business', 'Q4', 'Actual', 387),
 ('Departures', '2011-31-03 12:00:00 ', '2011', 56900, 'Visitors on Business', 'Q1', 'Actual', 389),
 ('Departures', '2011-30-06 12:00:00 ', '2011', 52400, 'Visitors on Business', 'Q2', 'Actual', 391),
 ('Departures', '2011-30-09 12:00:00 ', '2011', 31400, 'Visitors on Business', 'Q3', 'Actual', 393),
 ('Departures', '2001-30-09 12:00:00 ', '2001', 23300, 'Visitors on Business', 'Q3', 'Actual', 394),
 ('Departures', '2011-31-12 12:00:00 ', '2011', 57500, 'Visitors on Business', 'Q4', 'Actual', 395),
 ('Departures', '2002-30-09 12:00:00 ', '2002', 20400, 'Visitors on Business', 'Q3', 'Actual', 396),

### <font color="green">1.4 Challenges</font>

In [ ]:
%sql SELECT * FROM teaproduction LIMIT 5;

 * sqlite://
Done.

[('Production', 32.8, '01/25/2003 12:00:00 AM', 0),
 ('Production', 23.6, '02/25/2003 12:00:00 AM', 1),
 ('Production', 15.0, '03/25/2003 12:00:00 AM', 2),
 ('Production', 19.3, '04/25/2003 12:00:00 AM', 3),
 ('Production', 26.0, '05/25/2003 12:00:00 AM', 4)]

In [ ]:
# Challenge
# Using the tea_production dataset, which three dates had tea production 
# before the date with the most tea production?
#
%%sql 
SELECT SUBSTR(Date, 7, 4)|| '-' ||SUBSTR(Date, 1, 2)|| '-' ||SUBSTR(Date, 4, 2)|| ' ' ||SUBSTR(Date, 12, 9) AS Updated_Date
FROM teaproduction LIMIT 5;

 * sqlite://
Done.

[('2003-01-25 12:00:00 ',),
 ('2003-02-25 12:00:00 ',),
 ('2003-03-25 12:00:00 ',),
 ('2003-04-25 12:00:00 ',),
 ('2003-05-25 12:00:00 ',)]

In [ ]:
%%sql
UPDATE teaproduction
SET Date = SUBSTR(Date, 7, 4)|| '-' ||SUBSTR(Date, 1, 2)|| '-' ||SUBSTR(Date, 4, 2)|| ' ' ||SUBSTR(Date, 12, 9);
SELECT * FROM teaproduction;

 * sqlite://
407 rows affected.
Done.

[('Production', 32.8, '2003-01-25 12:00:00 ', 0),
 ('Production', 23.6, '2003-02-25 12:00:00 ', 1),
 ('Production', 15.0, '2003-03-25 12:00:00 ', 2),
 ('Production', 19.3, '2003-04-25 12:00:00 ', 3),
 ('Production', 26.0, '2003-05-25 12:00:00 ', 4),
 ('Production', 19.5, '2003-06-25 12:00:00 ', 5),
 ('Production', 18.9, '2003-07-25 12:00:00 ', 6),
 ('Production', 19.9, '2003-08-25 12:00:00 ', 7),
 ('Production', 26.4, '2003-09-25 12:00:00 ', 8),
 ('Production', 31.6, '2003-10-25 12:00:00 ', 9),
 ('Production', 27.0, '2003-11-25 12:00:00 ', 10),
 ('Production', 39.2, '2003-12-25 12:00:00 ', 11),
 ('Production', 31.1, '2004-01-25 12:00:00 ', 12),
 ('Production', 28.1, '2004-02-25 12:00:00 ', 13),
 ('Production', 28.9, '2004-03-25 12:00:00 ', 14),
 ('Production', 29.4, '2004-04-25 12:00:00 ', 15),
 ('Production', 28.4, '2004-05-25 12:00:00 ', 16),
 ('Production', 23.9, '2004-06-25 12:00:00 ', 17),
 ('Production', 18.6, '2004-07-25 12:00:00 ', 18),
 ('Production', 18.9, '2004-08-25 12:00:00 ', 19),
 ('Production', 23.0, '2004-09-25 12:00:00 ', 20),
 ('Production', 27.4, '2004-10-25 12:00:00 ', 21),
 ('Production', 32.0, '2004-11-25 12:00:00 ', 22),
 ('Production', 34.6, '2004-12-25 12:00:00 ', 23),
 ('Production', 34.1, '2005-01-25 12:00:00 ', 24),
 ('Production', 25.8, '2005-02-25 12:00:00 ', 25),
 ('Production', 24.8, '2005-03-25 12:00:00 ', 26),
 ('Production', 29.1, '2005-04-25 12:00:00 ', 27),
 ('Production', 28.8, '2005-05-25 12:00:00 ', 28),
 ('Production', 24.0, '2005-06-25 12:00:00 ', 29),
 ('Production', 20.8, '2005-07-25 12:00:00 ', 30),
 ('Production', 21.8, '2005-08-25 12:00:00 ', 31),
 ('Production', 26.9, '2005-09-25 12:00:00 ', 32),
 ('Production', 32.3, '2005-10-25 12:00:00 ', 33),
 ('Production', 30.0, '2005-11-25 12:00:00 ', 34),
 ('Production', 29.8, '2005-12-25 12:00:00 ', 35),
 ('Production', 17.9, '2006-01-25 12:00:00 ', 36),
 ('Production', 11.7, '2006-02-25 12:00:00 ', 37),
 ('Production', 19.9, '2006-03-25 12:00:00 ', 38),
 ('Production', 30.4, '2006-04-25 12:00:00 ', 39),
 ('Production', 26.4, '2006-05-25 12:00:00 ', 40),
 ('Production', 27.7, '2006-06-25 12:00:00 ', 41),
 ('Production', 23.8, '2006-07-25 12:00:00 ', 42),
 ('Production', 23.2, '2006-08-25 12:00:00 ', 43),
 ('Production', 28.6, '2006-09-25 12:00:00 ', 44),
 ('Production', 34.8, '2006-10-25 12:00:00 ', 45),
 ('Production', 31.6, '2006-11-25 12:00:00 ', 46),
 ('Production', 34.4, '2006-12-25 12:00:00 ', 47),
 ('Production', 41.6, '2007-01-25 12:00:00 ', 48),
 ('Production', 34.8, '2007-02-25 12:00:00 ', 49),
 ('Production', 32.2, '2007-03-25 12:00:00 ', 50),
 ('Production', 30.7, '2007-04-25 12:00:00 ', 51),
 ('Production', 32.1, '2007-05-25 12:00:00 ', 52),
 ('Production', 27.3, '2007-06-25 12:00:00 ', 53),
 ('Production', 22.7, '2007-07-25 12:00:00 ', 54),
 ('Production', 22.7, '2007-08-25 12:00:00 ', 55),
 ('Production', 28.9, '2007-09-25 12:00:00 ', 56),
 ('Production', 35.2, '2007-10-25 12:00:00 ', 57),
 ('Production', 32.3, '2007-11-25 12:00:00 ', 58),
 ('Production', 28.8, '2007-12-25 12:00:00 ', 59),
 ('Production', 29.7, '2008-01-25 12:00:00 ', 60),
 ('Production', 24.1, '2008-02-25 12:00:00 ', 61),
 ('Production', 16.9, '2008-03-25 12:00:00 ', 62),
 ('Production', 27.4, '2008-04-25 12:00:00 ', 63),
 ('Production', 36.4, '2008-05-25 12:00:00 ', 64),
 ('Production', 22.8, '2008-06-25 12:00:00 ', 65),
 ('Production', 24.2, '2008-07-25 12:00:00 ', 66),
 ('Production', 24.5, '2008-08-25 12:00:00 ', 67),
 ('Production', 32.0, '2008-09-25 12:00:00 ', 68),
 ('Production', 35.3, '2008-10-25 12:00:00 ', 69),
 ('Production', 34.4, '2008-11-25 12:00:00 ', 70),
 ('Production', 37.9, '2008-12-25 12:00:00 ', 71),
 ('Production', 25.5, '2009-01-25 12:00:00 ', 72),
 ('Production', 21.5, '2009-02-25 12:00:00 ', 73),
 ('Production', 18.8, '2009-03-25 12:00:00 ', 74),
 ('Production', 18.3, '2009-04-25 12:00:00 ', 75),
 ('Production', 29.8, '2009-05-25 12:00:00 ', 76),
 ('Production', 25.3, '2009-06-25 12:00:00 ', 77),
 ('Production', 21.5, '2009-07-25 12:00:00 ', 78),
 ('Production', 21.2, '2009-08-25 12:00:00 ', 79),
 ('Production', 27.4, '2009-09-25 12:00:00 ', 80),
 ('Production', 32.8, '2009-10-25 12:00:00 ', 81),
 ('Production', 35.9, '2009-11-25 12:00:00 ', 82),
 ('Production', 36.1, '2009-12-25 12:00:00 ', 83),
 ('Production', 37.7, '2010-01-25 12:00:00 ', 84),
 ('Production', 34.8, '2010-02-25 12:00:00 ', 85),
 ('Production', 39.2, '2010-03-25 12:00:00 ', 86),
 ('Production', 35.9, '2010-04-25 12:00:00 ', 87),
 ('Production', 35.6, '2010-05-25 12:00:00 ', 88),
 ('Production', 29.8, '2010-06-25 12:00:00 ', 89),
 ('Production', 24.4, '2010-07-25 12:00:00 ', 90),
 ('Production', 23.1, '2010-08-25 12:00:00 ', 91),
 ('Production', 28.8, '2010-09-25 12:00:00 ', 92),
 ('Production', 34.1, '2010-10-25 12:00:00 ', 93),
 ('Production', 37.0, '2010-11-25 12:00:00 ', 94),
 ('Production', 38.3, '2010-12-25 12:00:00 ', 95),
 ('Production', 35.9, '2011-01-25 12:00:00 ', 96),
 ('Production', 26.7, '2011-02-25 12:00:00 ', 97),
 ('Production', 22.4, '2011-03-25 12:00:00 ', 98),
 ('Production', 31.4, '2011-04-25 12:00:00 ', 99),
 ('Production', 32.8, '2011-05-25 12:00:00 ', 100),
 ('Production', 28.9, '2011-06-25 12:00:00 ', 101),
 ('Production', 26.3, '2011-07-25 12:00:00 ', 102),
 ('Production', 24.4, '2011-08-25 12:00:00 ', 103),
 ('Production', 30.5, '2011-09-25 12:00:00 ', 104),
 ('Production', 39.9, '2011-10-25 12:00:00 ', 105),
 ('Production', 36.8, '2011-11-25 12:00:00 ', 106),
 ('Production', 41.3, '2011-12-25 12:00:00 ', 107),
 ('Production', 36.2, '2012-01-25 12:00:00 ', 108),
 ('Production', 18.4, '2012-02-25 12:00:00 ', 109),
 ('Production', 17.8, '2012-03-25 12:00:00 ', 110),
 ('Production', 18.1, '2012-04-25 12:00:00 ', 111),
 ('Production', 37.3, '2012-05-25 12:00:00 ', 112),
 ('Production', 30.2, '2012-06-25 12:00:00 ', 113),
 ('Production', 24.3, '2012-07-25 12:00:00 ', 114),
 ('Production', 31.9, '2012-08-25 12:00:00 ', 115),
 ('Production', 33.5, '2012-09-25 12:00:00 ', 116),
 ('Production', 40.2, '2012-10-25 12:00:00 ', 117),
 ('Production', 39.9, '2012-11-25 12:00:00 ', 118),
 ('Production', 41.4, '2012-12-25 12:00:00 ', 119),
 ('Production', 45.3, '2013-01-25 12:00:00 ', 120),
 ('Production', 38.5, '2013-02-25 12:00:00 ', 121),
 ('Production', 33.3, '2013-03-25 12:00:00 ', 122),
 ('Production', 38.2, '2013-04-25 12:00:00 ', 123),
 ('Production', 39.6, '2013-05-25 12:00:00 ', 124),
 ('Production', 30.5, '2013-06-25 12:00:00 ', 125),
 ('Production', 26.2, '2013-07-25 12:00:00 ', 126),
 ('Production', 26.3, '2013-08-25 12:00:00 ', 127),
 ('Production', 32.8, '2013-09-25 12:00:00 ', 128),
 ('Production', 44.3, '2013-10-25 12:00:00 ', 129),
 ('Production', 35.5, '2013-11-25 12:00:00 ', 130),
 ('Production', 41.7, '2013-12-25 12:00:00 ', 131),
 ('Production', 44.9, '2014-01-25 12:00:00 ', 132),
 ('Production', 33.7, '2014-02-25 12:00:00 ', 133),
 ('Production', 33.3, '2014-03-25 12:00:00 ', 134),
 ('Production', 39.9, '2014-04-25 12:00:00 ', 135),
 ('Production', 41.1, '2014-05-25 12:00:00 ', 136),
 ('Production', 31.9, '2014-06-25 12:00:00 ', 137),
 ('Production', 30.8, '2014-07-25 12:00:00 ', 138),
 ('Production', 26.8, '2014-08-25 12:00:00 ', 139),
 ('Production', 33.3, '2014-09-25 12:00:00 ', 140),
 ('Production', 45.4, '2014-10-25 12:00:00 ', 141),
 ('Production', 38.6, '2014-11-25 12:00:00 ', 142),
 ('Production', 45.1, '2014-12-25 12:00:00 ', 143),
 ('Production', 41.7, '2015-01-25 12:00:00 ', 144),
 ('Production', 24.3, '2015-02-25 12:00:00 ', 145),
 ('Production', 15.7, '2015-03-25 12:00:00 ', 146),
 ('Production', 23.8, '2015-04-25 12:00:00 ', 147),
 ('Production', 37.5, '2015-05-25 12:00:00 ', 148),
 ('Production', 32.2, '2015-06-25 12:00:00 ', 149),
 ('Exports', 24.9, '2003-01-25 12:00:00 ', 150),
 ('Exports', 26.4, '2003-02-25 12:00:00 ', 151),
 ('Exports', 30.8, '2003-03-25 12:00:00 ', 152),
 ('Exports', 23.4, '2003-04-25 12:00:00 ', 153),
 ('Exports', 23.4, '2003-05-25 12:00:00 ', 154),
 ('Exports', 25.8, '2003-06-25 12:00:00 ', 155),
 ('Exports', 26.7, '2003-07-25 12:00:00 ', 156),
 ('Exports', 23.6, '2003-08-25 12:00:00 ', 157),
 ('Exports', 23.1, '2003-09-25 12:00:00 ', 158),
 ('Exports', 25.9, '2003-10-25 12:00:00 ', 159),
 ('Exports', 25.3, '2003-11-25 12:00:00 ', 160),
 ('Exports', 26.9, '2003-12-25 12:00:00 ', 161),
 ('Exports', 28.8, '2004-01-25 12:00:00 ', 162),
 ('Exports', 26.2, '2004-02-25 12:00:00 ', 163),
 ('Exports', 35.2, '2004-03-25 12:00:00 ', 164),
 ('Exports', 30.4, '2004-04-25 12:00:00 ', 165),
 ('Exports', 29.4, '2004-05-25 12:00:00 ', 166),
 ('Exports', 22.6, '2004-06-25 12:00:00 ', 167),
 ('Exports', 27.2, '2004-07-25 12:00:00 ', 168),
 ('Exports', 24.3, '2004-08-25 12:00:00 ', 169),
 ('Exports', 28.2, '2004-09-25 12:00:00 ', 170),
 ('Exports', 22.7, '2004-10-25 12:00:00 ', 171),
 ('Exports', 30.4, '2004-11-25 12:00:00 ', 172),
 ('Exports', 28.4, '2004-12-25 12:00:00 ', 173),
 ('Exports', 27.3, '2005-01-25 12:00:00 ', 174),
 ('Exports', 30.6, '2005-02-25 12:00:00 ', 175),
 ('Exports', 31.6, '2005-03-25 12:00:00 ', 176),
 ('Exports', 27.6, '2005-04-25 12:00:00 ', 177),
 ('Exports', 26.5, '2005-05-25 12:00:00 ', 178),
 ('Exports', 28.3, '2005-06-25 12:00:00 ', 179),
 ('Exports', 35.5, '2005-07-25 12:00:00 ', 180),
 ('Exports', 35.0, '2005-08-25 12:00:00 ', 181),
 ('Exports', 28.6, '2005-09-25 12:00:00 ', 182),
 ('Exports', 21.3, '2005-10-25 12:00:00 ', 183),
 ('Exports', 25.1, '2005-11-25 12:00:00 ', 184),
 ('Exports', 32.5, '2005-12-25 12:00:00 ', 185),
 ('Exports', 29.7, '2006-01-25 12:00:00 ', 186),
 ('Exports', 24.7, '2006-02-25 12:00:00 ', 187),
 ('Exports', 20.9, '2006-03-25 12:00:00 ', 188),
 ('Exports', 17.8, '2006-04-25 12:00:00 ', 189),
 ('Exports', 28.1, '2006-05-25 12:00:00 ', 190),
 ('Exports', 26.2, '2006-06-25 12:00:00 ', 191),
 ('Exports', 29.6, '2006-07-25 12:00:00 ', 192),
 ('Exports', 30.4, '2006-08-25 12:00:00 ', 193),
 ('Exports', 26.7, '2006-09-25 12:00:00 ', 194),
 ('Exports', 22.2, '2006-10-25 12:00:00 ', 195),
 ('Exports', 31.9, '2006-11-25 12:00:00 ', 196),
 ('Exports', 25.5, '2006-12-25 12:00:00 ', 197),
 ('Exports', 35.0, '2007-01-25 12:00:00 ', 198),
 ('Exports', 31.9, '2007-02-25 12:00:00 ', 199),
 ('Exports', 33.4, '2007-03-25 12:00:00 ', 200),
 ('Exports', 29.8, '2007-04-25 12:00:00 ', 201),
 ('Exports', 33.8, '2007-05-25 12:00:00 ', 202),
 ('Exports', 32.0, '2007-06-25 12:00:00 ', 203),
 ('Exports', 24.7, '2007-07-25 12:00:00 ', 204),
 ('Exports', 28.3, '2007-08-25 12:00:00 ', 205),
 ('Exports', 21.2, '2007-09-25 12:00:00 ', 206),
 ('Exports', 21.4, '2007-10-25 12:00:00 ', 207),
 ('Exports', 36.4, '2007-11-25 12:00:00 ', 208),
 ('Exports', 17.9, '2007-12-25 12:00:00 ', 209),
 ('Exports', 30.4, '2008-01-25 12:00:00 ', 210),
 ('Exports', 27.9, '2008-02-25 12:00:00 ', 211),
 ('Exports', 23.9, '2008-03-25 12:00:00 ', 212),
 ('Exports', 35.2, '2008-04-25 12:00:00 ', 213),
 ('Exports', 28.8, '2008-05-25 12:00:00 ', 214),
 ('Exports', 33.0, '2008-06-25 12:00:00 ', 215),
 ('Exports', 31.6, '2008-07-25 12:00:00 ', 216),
 ('Exports', 40.2, '2008-08-25 12:00:00 ', 217),
 ('Exports', 36.6, '2008-09-25 12:00:00 ', 218),
 ('Exports', 34.1, '2008-10-25 12:00:00 ', 219),
 ('Exports', 32.6, '2008-11-25 12:00:00 ', 220),
 ('Exports', 29.1, '2008-12-25 12:00:00 ', 221),
 ('Exports', 34.9, '2009-01-25 12:00:00 ', 222),
 ('Exports', 25.1, '2009-02-25 12:00:00 ', 223),
 ('Exports', 33.8, '2009-03-25 12:00:00 ', 224),
 ('Exports', 24.8, '2009-04-25 12:00:00 ', 225),
 ('Exports', 22.4, '2009-05-25 12:00:00 ', 226),
 ('Exports', 26.9, '2009-06-25 12:00:00 ', 227),
 ('Exports', 32.4, '2009-07-25 12:00:00 ', 228),
 ('Exports', 25.6, '2009-08-25 12:00:00 ', 229),
 ('Exports', 30.9, '2009-09-25 12:00:00 ', 230),
 ('Exports', 27.1, '2009-10-25 12:00:00 ', 231),
 ('Exports', 30.3, '2009-11-25 12:00:00 ', 232),
 ('Exports', 28.3, '2009-12-25 12:00:00 ', 233),
 ('Exports', 39.2, '2010-01-25 12:00:00 ', 234),
 ('Exports', 37.6, '2010-02-25 12:00:00 ', 235),
 ('Exports', 40.2, '2010-03-25 12:00:00 ', 236),
 ('Exports', 31.8, '2010-04-25 12:00:00 ', 237),
 ('Exports', 31.0, '2010-05-25 12:00:00 ', 238),
 ('Exports', 36.8, '2010-06-25 12:00:00 ', 239),
 ('Exports', 38.3, '2010-07-25 12:00:00 ', 240),
 ('Exports', 37.7, '2010-08-25 12:00:00 ', 241),
 ('Exports', 43.8, '2010-09-25 12:00:00 ', 242),
 ('Exports', 27.8, '2010-10-25 12:00:00 ', 243),
 ('Exports', 41.5, '2010-11-25 12:00:00 ', 244),
 ('Exports', 34.9, '2010-12-25 12:00:00 ', 245),
 ('Exports', 33.6, '2011-01-25 12:00:00 ', 246),
 ('Exports', 32.2, '2011-02-25 12:00:00 ', 247),
 ('Exports', 41.5, '2011-03-25 12:00:00 ', 248),
 ('Exports', 32.1, '2011-04-25 12:00:00 ', 249),
 ('Exports', 34.4, '2011-05-25 12:00:00 ', 250),
 ('Exports', 37.7, '2011-06-25 12:00:00 ', 251),
 ('Exports', 37.4, '2011-07-25 12:00:00 ', 252),
 ('Exports', 37.2, '2011-08-25 12:00:00 ', 253),
 ('Exports', 28.8, '2011-09-25 12:00:00 ', 254),
 ('Exports', 30.2, '2011-10-25 12:00:00 ', 255),
 ('Exports', 39.3, '2011-11-25 12:00:00 ', 256),
 ('Exports', 36.2, '2011-12-25 12:00:00 ', 257),
 ('Exports', 37.9, '2012-01-25 12:00:00 ', 258),
 ('Exports', 44.7, '2012-02-25 12:00:00 ', 259),
 ('Exports', 35.4, '2012-03-25 12:00:00 ', 260),
 ('Exports', 29.4, '2012-04-25 12:00:00 ', 261),
 ('Exports', 29.9, '2012-05-25 12:00:00 ', 262),
 ('Exports', 30.1, '2012-06-25 12:00:00 ', 263),
 ('Exports', 33.2, '2012-07-25 12:00:00 ', 264),
 ('Exports', 37.2, '2012-08-25 12:00:00 ', 265),
 ('Exports', 35.7, '2012-09-25 12:00:00 ', 266),
 ('Exports', 38.6, '2012-10-25 12:00:00 ', 267),
 ('Exports', 44.0, '2012-11-25 12:00:00 ', 268),
 ('Exports', 33.5, '2012-12-25 12:00:00 ', 269),
 ('Exports', 39.8, '2013-01-25 12:00:00 ', 270),
 ('Exports', 42.9, '2013-02-25 12:00:00 ', 271),
 ('Exports', 36.1, '2013-03-25 12:00:00 ', 272),
 ('Exports', 40.1, '2013-04-25 12:00:00 ', 273),
 ('Exports', 45.4, '2013-05-25 12:00:00 ', 274),
 ('Exports', 42.3, '2013-06-25 12:00:00 ', 275),
 ('Exports', 46.1, '2013-07-25 12:00:00 ', 276),
 ('Exports', 43.7, '2013-08-25 12:00:00 ', 277),
 ('Exports', 38.7, '2013-09-25 12:00:00 ', 278),
 ('Exports', 38.7, '2013-10-25 12:00:00 ', 279),
 ('Exports', 40.2, '2013-11-25 12:00:00 ', 280),
 ('Exports', 40.2, '2013-12-25 12:00:00 ', 281),
 ('Exports', 41.5, '2014-01-25 12:00:00 ', 282),
 ('Exports', 42.0, '2014-02-25 12:00:00 ', 283),
 ('Exports', 41.9, '2014-03-25 12:00:00 ', 284),
 ('Exports', 40.7, '2014-04-25 12:00:00 ', 285),
 ('Exports', 40.9, '2014-05-25 12:00:00 ', 286),
 ('Exports', 42.8, '2014-06-25 12:00:00 ', 287),
 ('Exports', 46.8, '2014-07-25 12:00:00 ', 288),
 ('Exports', 44.9, '2014-08-25 12:00:00 ', 289),
 ('Exports', 35.3, '2014-09-25 12:00:00 ', 290),
 ('Exports', 41.5, '2014-10-25 12:00:00 ', 291),
 ('Exports', 39.6, '2014-11-25 12:00:00 ', 292),
 ('Exports', 41.1, '2014-12-25 12:00:00 ', 293),
 ('Exports', 43.7, '2015-01-25 12:00:00 ', 294),
 ('Exports', 40.4, '2015-02-25 12:00:00 ', 295),
 ('Exports', 35.1, '2015-03-25 12:00:00 ', 296),
 ('Exports', 28.0, '2015-04-25 12:00:00 ', 297),
 ('Exports', 26.2, '2015-05-25 12:00:00 ', 298),
 ('Exports', 36.7, '2015-06-25 12:00:00 ', 299),
 ('Consumption', 1.1, '2008-01-25 12:00:00 ', 300),
 ('Consumption', 1.1, '2008-02-25 12:00:00 ', 301),
 ('Consumption', 1.1, '2008-03-25 12:00:00 ', 302),
 ('Consumption', 1.5, '2008-04-25 12:00:00 ', 303),
 ('Consumption', 2.1, '2008-05-25 12:00:00 ', 304),
 ('Consumption', 1.7, '2008-06-25 12:00:00 ', 305),
 ('Consumption', 1.1, '2008-07-25 12:00:00 ', 306),
 ('Consumption', 1.6, '2008-08-25 12:00:00 ', 307),
 ('Consumption', 1.3, '2008-09-25 12:00:00 ', 308),
 ('Consumption', 1.4, '2008-10-25 12:00:00 ', 309),
 ('Consumption', 1.5, '2008-11-25 12:00:00 ', 310),
 ('Consumption', 1.9, '2008-12-25 12:00:00 ', 311),
 ('Consumption', 1.5, '2009-01-25 12:00:00 ', 312),
 ('Consumption', 1.5, '2009-02-25 12:00:00 ', 313),
 ('Consumption', 1.4, '2009-03-25 12:00:00 ', 314),
 ('Consumption', 1.6, '2009-04-25 12:00:00 ', 315),
 ('Consumption', 1.6, '2009-05-25 12:00:00 ', 316),
 ('Consumption', 1.5, '2009-06-25 12:00:00 ', 317),
 ('Consumption', 1.3, '2009-07-25 12:00:00 ', 318),
 ('Consumption', 1.4, '2009-08-25 12:00:00 ', 319),
 ('Consumption', 1.4, '2009-09-25 12:00:00 ', 320),
 ('Consumption', 1.5, '2009-10-25 12:00:00 ', 321),
 ('Consumption', 1.5, '2009-11-25 12:00:00 ', 322),
 ('Consumption', 1.8, '2009-12-25 12:00:00 ', 323),
 ('Consumption', 1.4, '2010-01-25 12:00:00 ', 324),
 ('Consumption', 1.3, '2010-02-25 12:00:00 ', 325),
 ('Consumption', 1.3, '2010-03-25 12:00:00 ', 326),
 ('Consumption', 1.5, '2010-04-25 12:00:00 ', 327),
 ('Consumption', 1.6, '2010-05-25 12:00:00 ', 328),
 ('Consumption', 1.6, '2010-06-25 12:00:00 ', 329),
 ('Consumption', 1.5, '2010-07-25 12:00:00 ', 330),
 ('Consumption', 1.6, '2010-08-25 12:00:00 ', 331),
 ('Consumption', 1.8, '2010-09-25 12:00:00 ', 332),
 ('Consumption', 1.6, '2010-10-25 12:00:00 ', 333),
 ('Consumption', 1.7, '2010-11-25 12:00:00 ', 334),
 ('Consumption', 1.8, '2010-12-25 12:00:00 ', 335),
 ('Consumption', 1.4, '2011-01-25 12:00:00 ', 336),
 ('Consumption', 1.6, '2011-02-25 12:00:00 ', 337),
 ('Consumption', 1.5, '2011-03-25 12:00:00 ', 338),
 ('Consumption', 1.8, '2011-04-25 12:00:00 ', 339),
 ('Consumption', 2.0, '2011-05-25 12:00:00 ', 340),
 ('Consumption', 1.7, '2011-06-25 12:00:00 ', 341),
 ('Consumption', 1.5, '2011-07-25 12:00:00 ', 342),
 ('Consumption', 1.6, '2011-08-25 12:00:00 ', 343),
 ('Consumption', 1.9, '2011-09-25 12:00:00 ', 344),
 ('Consumption', 1.7, '2011-10-25 12:00:00 ', 345),
 ('Consumption', 1.7, '2011-11-25 12:00:00 ', 346),
 ('Consumption', 1.6, '2011-12-25 12:00:00 ', 347),
 ('Consumption', 1.3, '2012-01-25 12:00:00 ', 348),
 ('Consumption', 1.6, '2012-02-25 12:00:00 ', 349),
 ('Consumption', 1.6, '2012-03-25 12:00:00 ', 350),
 ('Consumption', 1.2, '2012-04-25 12:00:00 ', 351),
 ('Consumption', 1.5, '2012-05-25 12:00:00 ', 352),
 ('Consumption', 1.5, '2012-06-25 12:00:00 ', 353),
 ('Consumption', 1.5, '2012-07-25 12:00:00 ', 354),
 ('Consumption', 2.2, '2012-08-25 12:00:00 ', 355),
 ('Consumption', 2.6, '2012-09-25 12:00:00 ', 356),
 ('Consumption', 2.9, '2012-10-25 12:00:00 ', 357),
 ('Consumption', 2.8, '2012-11-25 12:00:00 ', 358),
 ('Consumption', 2.0, '2012-12-25 12:00:00 ', 359),
 ('Consumption', 2.2, '2013-01-25 12:00:00 ', 360),
 ('Consumption', 1.8, '2013-02-25 12:00:00 ', 361),
 ('Consumption', 1.7, '2013-03-25 12:00:00 ', 362),
 ('Consumption', 2.6, '2013-04-25 12:00:00 ', 363),
 ('Consumption', 2.2, '2013-05-25 12:00:00 ', 364),
 ('Consumption', 1.9, '2013-06-25 12:00:00 ', 365),
 ('Consumption', 1.7, '2013-07-25 12:00:00 ', 366),
 ('Consumption', 1.7, '2013-08-25 12:00:00 ', 367),
 ('Consumption', 2.0, '2013-09-25 12:00:00 ', 368),
 ('Consumption', 2.7, '2013-10-25 12:00:00 ', 369),
 ('Consumption', 3.1, '2013-11-25 12:00:00 ', 370),
 ('Consumption', 2.9, '2013-12-25 12:00:00 ', 371),
 ('Consumption', 3.1, '2014-01-25 12:00:00 ', 372),
 ('Consumption', 2.1, '2014-02-25 12:00:00 ', 373),
 ('Consumption', 2.5, '2014-03-25 12:00:00 ', 374),
 ('Consumption', 2.4, '2014-04-25 12:00:00 ', 375),
 ('Consumption', 3.6, '2014-05-25 12:00:00 ', 376),
 ('Consumption', 3.2, '2014-06-25 12:00:00 ', 377),
 ('Consumption', 2.6, '2014-07-25 12:00:00 ', 378),
 ('Consumption', 2.8, '2014-08-25 12:00:00 ', 379),
 ('Consumption', 2.7, '2014-09-25 12:00:00 ', 380),
 ('Consumption', 2.7, '2014-10-25 12:00:00 ', 381),
 ('Consumption', 2.4, '2014-11-25 12:00:00 ', 382),
 ('Consumption', 2.0, '2014-12-25 12:00:00 ', 383),
 ('Consumption', 2.5, '2015-01-25 12:00:00 ', 384),
 ('Consumption', 2.3, '2015-02-25 12:00:00 ', 385),
 ('Consumption', 1.9, '2015-03-25 12:00:00 ', 386),
 ('Consumption', 1.4, '2015-04-25 12:00:00 ', 387),
 ('Consumption', 1.6, '2015-05-25 12:00:00 ', 388),
 ('Consumption', 3.1, '2015-06-25 12:00:00 ', 389),
 ('Production', 30.94, '2015-07-25 12:00:00 ', 390),
 ('Production', 28.41, '2015-08-25 12:00:00 ', 391),
 ('Production', 36.84, '2015-09-25 12:00:00 ', 392),
 ('Production', 41.34, '2015-10-25 12:00:00 ', 393),
 ('Production', 40.38, '2015-11-25 12:00:00 ', 394),

In [ ]:
%sql SELECT * FROM teaproduction LIMIT 5;

 * sqlite://
Done.

[('Production', 32.8, '2003-01-25 12:00:00 ', 0),
 ('Production', 23.6, '2003-02-25 12:00:00 ', 1),
 ('Production', 15.0, '2003-03-25 12:00:00 ', 2),
 ('Production', 19.3, '2003-04-25 12:00:00 ', 3),
 ('Production', 26.0, '2003-05-25 12:00:00 ', 4)]

In [ ]:
# Deteremine the date when the tea production was high
%sql SELECT MAX(Millions_in_KGS_), Date FROM teaproduction WHERE Activity_in_Tea_Sector = 'Production';

 * sqlite://
Done.

[(45.4, '2014-10-25 12:00:00 ')]

In [ ]:
# Challenge
# Using the tea_production dataset, which three dates had tea production 
# before the date with the most tea production?
#
%%sql
SELECT Date FROM teaproduction
WHERE Date < '2014-10-25 12:00:00' AND Activity_in_Tea_Sector = 'Production' ORDER BY Date DESC
LIMIT 3;

 * sqlite://
Done.

[('2014-09-25 12:00:00 ',),
 ('2014-08-25 12:00:00 ',),
 ('2014-07-25 12:00:00 ',)]